package thousandlish;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.LinkedList;
import java.util.Scanner;

//PROGRAMA FEITO POR FELIPE( my Instagram and TikTok --> @l1p3fe)

public class ThousandlishRun {
	
	public static void main(String[] args) throws IOException {
		
		//INICIO [CRIA-SE O ARQUIVO COM AS 3K MOST COMMON WORDS IN ENGLISH]
		
		//SE VOCÊ TIVER PROBLEMAS EM LER O ARQUIVO .txt DAS PALAVRAS, EXECUTE ESTE CÓDIGO ABAIXO PARA 
		//FAZER O JAVA ESCREVER UM ARQUIVO COM AS PALAVRAS. O DESENVOLVEDOR CRIADOR DESTE PROGRAMA
		//TEVE UM PROBLEMA ASSIM E FEZ ESTE MÉTODO PARA FUNCIONAR O PROGRAMA.
	
//		OutputStream fos = new FileOutputStream("3mpei.txt");
//		Writer osw = new OutputStreamWriter(fos);
//		BufferedWriter bw = new BufferedWriter(osw);
//		
//		
//		//ACRESCENTA-SE AS PALAVRAS NO ARQUIVO;
//		
//		bw.write("a\r\n"
//				+ "abandon\r\n"
//				+ "ability\r\n"
//				+ "able\r\n"
//				+ "abortion\r\n"
//				+ "about\r\n"
//				+ "above\r\n"
//				+ "abroad\r\n"
//				+ "absence\r\n"
//				+ "absolute\r\n"
//				+ "absolutely\r\n"
//				+ "absorb\r\n"
//				+ "abuse\r\n"
//				+ "academic\r\n"
//				+ "accept\r\n"
//				+ "access\r\n"
//				+ "accident\r\n"
//				+ "accompany\r\n"
//				+ "accomplish\r\n"
//				+ "according\r\n"
//				+ "account\r\n"
//				+ "accurate\r\n"
//				+ "accuse\r\n"
//				+ "achieve\r\n"
//				+ "achievement\r\n"
//				+ "acid\r\n"
//				+ "acknowledge\r\n"
//				+ "acquire\r\n"
//				+ "across\r\n"
//				+ "act\r\n"
//				+ "action\r\n"
//				+ "active\r\n"
//				+ "activist\r\n"
//				+ "activity\r\n"
//				+ "actor\r\n"
//				+ "actress\r\n"
//				+ "actual\r\n"
//				+ "actually\r\n"
//				+ "ad\r\n"
//				+ "adapt\r\n"
//				+ "add\r\n"
//				+ "addition\r\n"
//				+ "additional\r\n"
//				+ "address\r\n"
//				+ "adequate\r\n"
//				+ "adjust\r\n"
//				+ "adjustment\r\n"
//				+ "administration\r\n"
//				+ "administrator\r\n"
//				+ "admire\r\n"
//				+ "admission\r\n"
//				+ "admit\r\n"
//				+ "adolescent\r\n"
//				+ "adopt\r\n"
//				+ "adult\r\n"
//				+ "advance\r\n"
//				+ "advanced\r\n"
//				+ "advantage\r\n"
//				+ "adventure\r\n"
//				+ "advertising\r\n"
//				+ "advice\r\n"
//				+ "advise\r\n"
//				+ "adviser\r\n"
//				+ "advocate\r\n"
//				+ "affair\r\n"
//				+ "affect\r\n"
//				+ "afford\r\n"
//				+ "afraid\r\n"
//				+ "African\r\n"
//				+ "African-American\r\n"
//				+ "after\r\n"
//				+ "afternoon\r\n"
//				+ "again\r\n"
//				+ "against\r\n"
//				+ "age\r\n"
//				+ "agency\r\n"
//				+ "agenda\r\n"
//				+ "agent\r\n"
//				+ "aggressive\r\n"
//				+ "ago\r\n"
//				+ "agree\r\n"
//				+ "agreement\r\n"
//				+ "agricultural\r\n"
//				+ "ah\r\n"
//				+ "ahead\r\n"
//				+ "aid\r\n"
//				+ "aide\r\n"
//				+ "AIDS\r\n"
//				+ "aim\r\n"
//				+ "air\r\n"
//				+ "aircraft\r\n"
//				+ "airline\r\n"
//				+ "airport\r\n"
//				+ "album\r\n"
//				+ "alcohol\r\n"
//				+ "alive\r\n"
//				+ "all\r\n"
//				+ "alliance\r\n"
//				+ "allow\r\n"
//				+ "ally\r\n"
//				+ "almost\r\n"
//				+ "alone\r\n"
//				+ "along\r\n"
//				+ "already\r\n"
//				+ "also\r\n"
//				+ "alter\r\n"
//				+ "alternative\r\n"
//				+ "although\r\n"
//				+ "always\r\n"
//				+ "AM\r\n"
//				+ "amazing\r\n"
//				+ "American\r\n"
//				+ "among\r\n"
//				+ "amount\r\n"
//				+ "analysis\r\n"
//				+ "analyst\r\n"
//				+ "analyze\r\n"
//				+ "ancient\r\n"
//				+ "and\r\n"
//				+ "anger\r\n"
//				+ "angle\r\n"
//				+ "angry\r\n"
//				+ "animal\r\n"
//				+ "anniversary\r\n"
//				+ "announce\r\n"
//				+ "annual\r\n"
//				+ "another\r\n"
//				+ "answer\r\n"
//				+ "anticipate\r\n"
//				+ "anxiety\r\n"
//				+ "any\r\n"
//				+ "anybody\r\n"
//				+ "anymore\r\n"
//				+ "anyone\r\n"
//				+ "anything\r\n"
//				+ "anyway\r\n"
//				+ "anywhere\r\n"
//				+ "apart\r\n"
//				+ "apartment\r\n"
//				+ "apparent\r\n"
//				+ "apparently\r\n"
//				+ "appeal\r\n"
//				+ "appear\r\n"
//				+ "appearance\r\n"
//				+ "apple\r\n"
//				+ "application\r\n"
//				+ "apply\r\n"
//				+ "appoint\r\n"
//				+ "appointment\r\n"
//				+ "appreciate\r\n"
//				+ "approach\r\n"
//				+ "appropriate\r\n"
//				+ "approval\r\n"
//				+ "approve\r\n"
//				+ "approximately\r\n"
//				+ "Arab\r\n"
//				+ "architect\r\n"
//				+ "area\r\n"
//				+ "argue\r\n"
//				+ "argument\r\n"
//				+ "arise\r\n"
//				+ "arm\r\n"
//				+ "armed\r\n"
//				+ "army\r\n"
//				+ "around\r\n"
//				+ "arrange\r\n"
//				+ "arrangement\r\n"
//				+ "arrest\r\n"
//				+ "arrival\r\n"
//				+ "arrive\r\n"
//				+ "art\r\n"
//				+ "article\r\n"
//				+ "artist\r\n"
//				+ "artistic\r\n"
//				+ "as\r\n"
//				+ "Asian\r\n"
//				+ "aside\r\n"
//				+ "ask\r\n"
//				+ "asleep\r\n"
//				+ "aspect\r\n"
//				+ "assault\r\n"
//				+ "assert\r\n"
//				+ "assess\r\n"
//				+ "assessment\r\n"
//				+ "asset\r\n"
//				+ "assign\r\n"
//				+ "assignment\r\n"
//				+ "assist\r\n"
//				+ "assistance\r\n"
//				+ "assistant\r\n"
//				+ "associate\r\n"
//				+ "association\r\n"
//				+ "assume\r\n"
//				+ "assumption\r\n"
//				+ "assure\r\n"
//				+ "at\r\n"
//				+ "athlete\r\n"
//				+ "athletic\r\n"
//				+ "atmosphere\r\n"
//				+ "attach\r\n"
//				+ "attack\r\n"
//				+ "attempt\r\n"
//				+ "attend\r\n"
//				+ "attention\r\n"
//				+ "attitude\r\n"
//				+ "attorney\r\n"
//				+ "attract\r\n"
//				+ "attractive\r\n"
//				+ "attribute\r\n"
//				+ "audience\r\n"
//				+ "author\r\n"
//				+ "authority\r\n"
//				+ "auto\r\n"
//				+ "available\r\n"
//				+ "average\r\n"
//				+ "avoid\r\n"
//				+ "award\r\n"
//				+ "aware\r\n"
//				+ "awareness\r\n"
//				+ "away\r\n"
//				+ "awful\r\n"
//				+ "baby\r\n"
//				+ "back\r\n"
//				+ "background\r\n"
//				+ "bad\r\n"
//				+ "badly\r\n"
//				+ "bag\r\n"
//				+ "bake\r\n"
//				+ "balance\r\n"
//				+ "ball\r\n"
//				+ "ban\r\n"
//				+ "band\r\n"
//				+ "bank\r\n"
//				+ "bar\r\n"
//				+ "barely\r\n"
//				+ "barrel\r\n"
//				+ "barrier\r\n"
//				+ "base\r\n"
//				+ "baseball\r\n"
//				+ "basic\r\n"
//				+ "basically\r\n"
//				+ "basis\r\n"
//				+ "basket\r\n"
//				+ "basketball\r\n"
//				+ "bathroom\r\n"
//				+ "battery\r\n"
//				+ "battle\r\n"
//				+ "be\r\n"
//				+ "beach\r\n"
//				+ "bean\r\n"
//				+ "bear\r\n"
//				+ "beat\r\n"
//				+ "beautiful\r\n"
//				+ "beauty\r\n"
//				+ "because\r\n"
//				+ "become\r\n"
//				+ "bed\r\n"
//				+ "bedroom\r\n"
//				+ "beer\r\n"
//				+ "before\r\n"
//				+ "begin\r\n"
//				+ "beginning\r\n"
//				+ "behavior\r\n"
//				+ "behind\r\n"
//				+ "being\r\n"
//				+ "belief\r\n"
//				+ "believe\r\n"
//				+ "bell\r\n"
//				+ "belong\r\n"
//				+ "below\r\n"
//				+ "belt\r\n"
//				+ "bench\r\n"
//				+ "bend\r\n"
//				+ "beneath\r\n"
//				+ "benefit\r\n"
//				+ "beside\r\n"
//				+ "besides\r\n"
//				+ "best\r\n"
//				+ "bet\r\n"
//				+ "better\r\n"
//				+ "between\r\n"
//				+ "beyond\r\n"
//				+ "Bible\r\n"
//				+ "big\r\n"
//				+ "bike\r\n"
//				+ "bill\r\n"
//				+ "billion\r\n"
//				+ "bind\r\n"
//				+ "biological\r\n"
//				+ "bird\r\n"
//				+ "birth\r\n"
//				+ "birthday\r\n"
//				+ "bit\r\n"
//				+ "bite\r\n"
//				+ "black\r\n"
//				+ "blade\r\n"
//				+ "blame\r\n"
//				+ "blanket\r\n"
//				+ "blind\r\n"
//				+ "block\r\n"
//				+ "blood\r\n"
//				+ "blow\r\n"
//				+ "blue\r\n"
//				+ "board\r\n"
//				+ "boat\r\n"
//				+ "body\r\n"
//				+ "bomb\r\n"
//				+ "bombing\r\n"
//				+ "bond\r\n"
//				+ "bone\r\n"
//				+ "book\r\n"
//				+ "boom\r\n"
//				+ "boot\r\n"
//				+ "border\r\n"
//				+ "born\r\n"
//				+ "borrow\r\n"
//				+ "boss\r\n"
//				+ "both\r\n"
//				+ "bother\r\n"
//				+ "bottle\r\n"
//				+ "bottom\r\n"
//				+ "boundary\r\n"
//				+ "bowl\r\n"
//				+ "box\r\n"
//				+ "boy\r\n"
//				+ "boyfriend\r\n"
//				+ "brain\r\n"
//				+ "branch\r\n"
//				+ "brand\r\n"
//				+ "bread\r\n"
//				+ "break\r\n"
//				+ "breakfast\r\n"
//				+ "breast\r\n"
//				+ "breath\r\n"
//				+ "breathe\r\n"
//				+ "brick\r\n"
//				+ "bridge\r\n"
//				+ "brief\r\n"
//				+ "briefly\r\n"
//				+ "bright\r\n"
//				+ "brilliant\r\n"
//				+ "bring\r\n"
//				+ "British\r\n"
//				+ "broad\r\n"
//				+ "broken\r\n"
//				+ "brother\r\n"
//				+ "brown\r\n"
//				+ "brush\r\n"
//				+ "buck\r\n"
//				+ "budget\r\n"
//				+ "build\r\n"
//				+ "building\r\n"
//				+ "bullet\r\n"
//				+ "bunch\r\n"
//				+ "burden\r\n"
//				+ "burn\r\n"
//				+ "bury\r\n"
//				+ "bus\r\n"
//				+ "business\r\n"
//				+ "busy\r\n"
//				+ "but\r\n"
//				+ "butter\r\n"
//				+ "button\r\n"
//				+ "buy\r\n"
//				+ "buyer\r\n"
//				+ "by\r\n"
//				+ "cabin\r\n"
//				+ "cabinet\r\n"
//				+ "cable\r\n"
//				+ "cake\r\n"
//				+ "calculate\r\n"
//				+ "call\r\n"
//				+ "camera\r\n"
//				+ "camp\r\n"
//				+ "campaign\r\n"
//				+ "campus\r\n"
//				+ "can\r\n"
//				+ "Canadian\r\n"
//				+ "cancer\r\n"
//				+ "candidate\r\n"
//				+ "cap\r\n"
//				+ "capability\r\n"
//				+ "capable\r\n"
//				+ "capacity\r\n"
//				+ "capital\r\n"
//				+ "captain\r\n"
//				+ "capture\r\n"
//				+ "car\r\n"
//				+ "carbon\r\n"
//				+ "card\r\n"
//				+ "care\r\n"
//				+ "career\r\n"
//				+ "careful\r\n"
//				+ "carefully\r\n"
//				+ "carrier\r\n"
//				+ "carry\r\n"
//				+ "case\r\n"
//				+ "cash\r\n"
//				+ "cast\r\n"
//				+ "cat\r\n"
//				+ "catch\r\n"
//				+ "category\r\n"
//				+ "Catholic\r\n"
//				+ "cause\r\n"
//				+ "ceiling\r\n"
//				+ "celebrate\r\n"
//				+ "celebration\r\n"
//				+ "celebrity\r\n"
//				+ "cell\r\n"
//				+ "center\r\n"
//				+ "central\r\n"
//				+ "century\r\n"
//				+ "CEO\r\n"
//				+ "ceremony\r\n"
//				+ "certain\r\n"
//				+ "certainly\r\n"
//				+ "chain\r\n"
//				+ "chair\r\n"
//				+ "chairman\r\n"
//				+ "challenge\r\n"
//				+ "chamber\r\n"
//				+ "champion\r\n"
//				+ "championship\r\n"
//				+ "chance\r\n"
//				+ "change\r\n"
//				+ "changing\r\n"
//				+ "channel\r\n"
//				+ "chapter\r\n"
//				+ "character\r\n"
//				+ "characteristic\r\n"
//				+ "characterize\r\n"
//				+ "charge\r\n"
//				+ "charity\r\n"
//				+ "chart\r\n"
//				+ "chase\r\n"
//				+ "cheap\r\n"
//				+ "check\r\n"
//				+ "cheek\r\n"
//				+ "cheese\r\n"
//				+ "chef\r\n"
//				+ "chemical\r\n"
//				+ "chest\r\n"
//				+ "chicken\r\n"
//				+ "chief\r\n"
//				+ "child\r\n"
//				+ "childhood\r\n"
//				+ "Chinese\r\n"
//				+ "chip\r\n"
//				+ "chocolate\r\n"
//				+ "choice\r\n"
//				+ "cholesterol\r\n"
//				+ "choose\r\n"
//				+ "Christian\r\n"
//				+ "Christmas\r\n"
//				+ "church\r\n"
//				+ "cigarette\r\n"
//				+ "circle\r\n"
//				+ "circumstance\r\n"
//				+ "cite\r\n"
//				+ "citizen\r\n"
//				+ "city\r\n"
//				+ "civil\r\n"
//				+ "civilian\r\n"
//				+ "claim\r\n"
//				+ "class\r\n"
//				+ "classic\r\n"
//				+ "classroom\r\n"
//				+ "clean\r\n"
//				+ "clear\r\n"
//				+ "clearly\r\n"
//				+ "client\r\n"
//				+ "climate\r\n"
//				+ "climb\r\n"
//				+ "clinic\r\n"
//				+ "clinical\r\n"
//				+ "clock\r\n"
//				+ "close\r\n"
//				+ "closely\r\n"
//				+ "closer\r\n"
//				+ "clothes\r\n"
//				+ "clothing\r\n"
//				+ "cloud\r\n"
//				+ "club\r\n"
//				+ "clue\r\n"
//				+ "cluster\r\n"
//				+ "coach\r\n"
//				+ "coal\r\n"
//				+ "coalition\r\n"
//				+ "coast\r\n"
//				+ "coat\r\n"
//				+ "code\r\n"
//				+ "coffee\r\n"
//				+ "cognitive\r\n"
//				+ "cold\r\n"
//				+ "collapse\r\n"
//				+ "colleague\r\n"
//				+ "collect\r\n"
//				+ "collection\r\n"
//				+ "collective\r\n"
//				+ "college\r\n"
//				+ "colonial\r\n"
//				+ "color\r\n"
//				+ "column\r\n"
//				+ "combination\r\n"
//				+ "combine\r\n"
//				+ "come\r\n"
//				+ "comedy\r\n"
//				+ "comfort\r\n"
//				+ "comfortable\r\n"
//				+ "command\r\n"
//				+ "commander\r\n"
//				+ "comment\r\n"
//				+ "commercial\r\n"
//				+ "commission\r\n"
//				+ "commit\r\n"
//				+ "commitment\r\n"
//				+ "committee\r\n"
//				+ "common\r\n"
//				+ "communicate\r\n"
//				+ "communication\r\n"
//				+ "community\r\n"
//				+ "company\r\n"
//				+ "compare\r\n"
//				+ "comparison\r\n"
//				+ "compete\r\n"
//				+ "competition\r\n"
//				+ "competitive\r\n"
//				+ "competitor\r\n"
//				+ "complain\r\n"
//				+ "complaint\r\n"
//				+ "complete\r\n"
//				+ "completely\r\n"
//				+ "complex\r\n"
//				+ "complicated\r\n"
//				+ "component\r\n"
//				+ "compose\r\n"
//				+ "composition\r\n"
//				+ "comprehensive\r\n"
//				+ "computer\r\n"
//				+ "concentrate\r\n"
//				+ "concentration\r\n"
//				+ "concept\r\n"
//				+ "concern\r\n"
//				+ "concerned\r\n"
//				+ "concert\r\n"
//				+ "conclude\r\n"
//				+ "conclusion\r\n"
//				+ "concrete\r\n"
//				+ "condition\r\n"
//				+ "conduct\r\n"
//				+ "conference\r\n"
//				+ "confidence\r\n"
//				+ "confident\r\n"
//				+ "confirm\r\n"
//				+ "conflict\r\n"
//				+ "confront\r\n"
//				+ "confusion\r\n"
//				+ "Congress\r\n"
//				+ "congressional\r\n"
//				+ "connect\r\n"
//				+ "connection\r\n"
//				+ "consciousness\r\n"
//				+ "consensus\r\n"
//				+ "consequence\r\n"
//				+ "conservative\r\n"
//				+ "consider\r\n"
//				+ "considerable\r\n"
//				+ "consideration\r\n"
//				+ "consist\r\n"
//				+ "consistent\r\n"
//				+ "constant\r\n"
//				+ "constantly\r\n"
//				+ "constitute\r\n"
//				+ "constitutional\r\n"
//				+ "construct\r\n"
//				+ "construction\r\n"
//				+ "consultant\r\n"
//				+ "consume\r\n"
//				+ "consumer\r\n"
//				+ "consumption\r\n"
//				+ "contact\r\n"
//				+ "contain\r\n"
//				+ "container\r\n"
//				+ "contemporary\r\n"
//				+ "content\r\n"
//				+ "contest\r\n"
//				+ "context\r\n"
//				+ "continue\r\n"
//				+ "continued\r\n"
//				+ "contract\r\n"
//				+ "contrast\r\n"
//				+ "contribute\r\n"
//				+ "contribution\r\n"
//				+ "control\r\n"
//				+ "controversial\r\n"
//				+ "controversy\r\n"
//				+ "convention\r\n"
//				+ "conventional\r\n"
//				+ "conversation\r\n"
//				+ "convert\r\n"
//				+ "conviction\r\n"
//				+ "convince\r\n"
//				+ "cook\r\n"
//				+ "cookie\r\n"
//				+ "cooking\r\n"
//				+ "cool\r\n"
//				+ "cooperation\r\n"
//				+ "cop\r\n"
//				+ "cope\r\n"
//				+ "copy\r\n"
//				+ "core\r\n"
//				+ "corn\r\n"
//				+ "corner\r\n"
//				+ "corporate\r\n"
//				+ "corporation\r\n"
//				+ "correct\r\n"
//				+ "correspondent\r\n"
//				+ "cost\r\n"
//				+ "cotton\r\n"
//				+ "couch\r\n"
//				+ "could\r\n"
//				+ "council\r\n"
//				+ "counselor\r\n"
//				+ "count\r\n"
//				+ "counter\r\n"
//				+ "country\r\n"
//				+ "county\r\n"
//				+ "couple\r\n"
//				+ "courage\r\n"
//				+ "course\r\n"
//				+ "court\r\n"
//				+ "cousin\r\n"
//				+ "cover\r\n"
//				+ "coverage\r\n"
//				+ "cow\r\n"
//				+ "crack\r\n"
//				+ "craft\r\n"
//				+ "crash\r\n"
//				+ "crazy\r\n"
//				+ "cream\r\n"
//				+ "create\r\n"
//				+ "creation\r\n"
//				+ "creative\r\n"
//				+ "creature\r\n"
//				+ "credit\r\n"
//				+ "crew\r\n"
//				+ "crime\r\n"
//				+ "criminal\r\n"
//				+ "crisis\r\n"
//				+ "criteria\r\n"
//				+ "critic\r\n"
//				+ "critical\r\n"
//				+ "criticism\r\n"
//				+ "criticize\r\n"
//				+ "crop\r\n"
//				+ "cross\r\n"
//				+ "crowd\r\n"
//				+ "crucial\r\n"
//				+ "cry\r\n"
//				+ "cultural\r\n"
//				+ "culture\r\n"
//				+ "cup\r\n"
//				+ "curious\r\n"
//				+ "current\r\n"
//				+ "currently\r\n"
//				+ "curriculum\r\n"
//				+ "custom\r\n"
//				+ "customer\r\n"
//				+ "cut\r\n"
//				+ "cycle\r\n"
//				+ "dad\r\n"
//				+ "daily\r\n"
//				+ "damage\r\n"
//				+ "dance\r\n"
//				+ "danger\r\n"
//				+ "dangerous\r\n"
//				+ "dare\r\n"
//				+ "dark\r\n"
//				+ "darkness\r\n"
//				+ "data\r\n"
//				+ "date\r\n"
//				+ "daughter\r\n"
//				+ "day\r\n"
//				+ "dead\r\n"
//				+ "deal\r\n"
//				+ "dealer\r\n"
//				+ "dear\r\n"
//				+ "death\r\n"
//				+ "debate\r\n"
//				+ "debt\r\n"
//				+ "decade\r\n"
//				+ "decide\r\n"
//				+ "decision\r\n"
//				+ "deck\r\n"
//				+ "declare\r\n"
//				+ "decline\r\n"
//				+ "decrease\r\n"
//				+ "deep\r\n"
//				+ "deeply\r\n"
//				+ "deer\r\n"
//				+ "defeat\r\n"
//				+ "defend\r\n"
//				+ "defendant\r\n"
//				+ "defense\r\n"
//				+ "defensive\r\n"
//				+ "deficit\r\n"
//				+ "define\r\n"
//				+ "definitely\r\n"
//				+ "definition\r\n"
//				+ "degree\r\n"
//				+ "delay\r\n"
//				+ "deliver\r\n"
//				+ "delivery\r\n"
//				+ "demand\r\n"
//				+ "democracy\r\n"
//				+ "Democrat\r\n"
//				+ "democratic\r\n"
//				+ "demonstrate\r\n"
//				+ "demonstration\r\n"
//				+ "deny\r\n"
//				+ "department\r\n"
//				+ "depend\r\n"
//				+ "dependent\r\n"
//				+ "depending\r\n"
//				+ "depict\r\n"
//				+ "depression\r\n"
//				+ "depth\r\n"
//				+ "deputy\r\n"
//				+ "derive\r\n"
//				+ "describe\r\n"
//				+ "description\r\n"
//				+ "desert\r\n"
//				+ "deserve\r\n"
//				+ "design\r\n"
//				+ "designer\r\n"
//				+ "desire\r\n"
//				+ "desk\r\n"
//				+ "desperate\r\n"
//				+ "despite\r\n"
//				+ "destroy\r\n"
//				+ "destruction\r\n"
//				+ "detail\r\n"
//				+ "detailed\r\n"
//				+ "detect\r\n"
//				+ "determine\r\n"
//				+ "develop\r\n"
//				+ "developing\r\n"
//				+ "development\r\n"
//				+ "device\r\n"
//				+ "devote\r\n"
//				+ "dialogue\r\n"
//				+ "die\r\n"
//				+ "diet\r\n"
//				+ "differ\r\n"
//				+ "difference\r\n"
//				+ "different\r\n"
//				+ "differently\r\n"
//				+ "difficult\r\n"
//				+ "difficulty\r\n"
//				+ "dig\r\n"
//				+ "digital\r\n"
//				+ "dimension\r\n"
//				+ "dining\r\n"
//				+ "dinner\r\n"
//				+ "direct\r\n"
//				+ "direction\r\n"
//				+ "directly\r\n"
//				+ "director\r\n"
//				+ "dirt\r\n"
//				+ "dirty\r\n"
//				+ "disability\r\n"
//				+ "disagree\r\n"
//				+ "disappear\r\n"
//				+ "disaster\r\n"
//				+ "discipline\r\n"
//				+ "discourse\r\n"
//				+ "discover\r\n"
//				+ "discovery\r\n"
//				+ "discrimination\r\n"
//				+ "discuss\r\n"
//				+ "discussion\r\n"
//				+ "disease\r\n"
//				+ "dish\r\n"
//				+ "dismiss\r\n"
//				+ "disorder\r\n"
//				+ "display\r\n"
//				+ "dispute\r\n"
//				+ "distance\r\n"
//				+ "distant\r\n"
//				+ "distinct\r\n"
//				+ "distinction\r\n"
//				+ "distinguish\r\n"
//				+ "distribute\r\n"
//				+ "distribution\r\n"
//				+ "district\r\n"
//				+ "diverse\r\n"
//				+ "diversity\r\n"
//				+ "divide\r\n"
//				+ "division\r\n"
//				+ "divorce\r\n"
//				+ "DNA\r\n"
//				+ "do\r\n"
//				+ "doctor\r\n"
//				+ "document\r\n"
//				+ "dog\r\n"
//				+ "domestic\r\n"
//				+ "dominant\r\n"
//				+ "dominate\r\n"
//				+ "door\r\n"
//				+ "double\r\n"
//				+ "doubt\r\n"
//				+ "down\r\n"
//				+ "downtown\r\n"
//				+ "dozen\r\n"
//				+ "draft\r\n"
//				+ "drag\r\n"
//				+ "drama\r\n"
//				+ "dramatic\r\n"
//				+ "dramatically\r\n"
//				+ "draw\r\n"
//				+ "drawing\r\n"
//				+ "dream\r\n"
//				+ "dress\r\n"
//				+ "drink\r\n"
//				+ "drive\r\n"
//				+ "driver\r\n"
//				+ "drop\r\n"
//				+ "drug\r\n"
//				+ "dry\r\n"
//				+ "due\r\n"
//				+ "during\r\n"
//				+ "dust\r\n"
//				+ "duty\r\n"
//				+ "each\r\n"
//				+ "eager\r\n"
//				+ "ear\r\n"
//				+ "early\r\n"
//				+ "earn\r\n"
//				+ "earnings\r\n"
//				+ "earth\r\n"
//				+ "ease\r\n"
//				+ "easily\r\n"
//				+ "east\r\n"
//				+ "eastern\r\n"
//				+ "easy\r\n"
//				+ "eat\r\n"
//				+ "economic\r\n"
//				+ "economics\r\n"
//				+ "economist\r\n"
//				+ "economy\r\n"
//				+ "edge\r\n"
//				+ "edition\r\n"
//				+ "editor\r\n"
//				+ "educate\r\n"
//				+ "education\r\n"
//				+ "educational\r\n"
//				+ "educator\r\n"
//				+ "effect\r\n"
//				+ "effective\r\n"
//				+ "effectively\r\n"
//				+ "efficiency\r\n"
//				+ "efficient\r\n"
//				+ "effort\r\n"
//				+ "egg\r\n"
//				+ "eight\r\n"
//				+ "either\r\n"
//				+ "elderly\r\n"
//				+ "elect\r\n"
//				+ "election\r\n"
//				+ "electric\r\n"
//				+ "electricity\r\n"
//				+ "electronic\r\n"
//				+ "element\r\n"
//				+ "elementary\r\n"
//				+ "eliminate\r\n"
//				+ "elite\r\n"
//				+ "else\r\n"
//				+ "elsewhere\r\n"
//				+ "e-mail\r\n"
//				+ "embrace\r\n"
//				+ "emerge\r\n"
//				+ "emergency\r\n"
//				+ "emission\r\n"
//				+ "emotion\r\n"
//				+ "emotional\r\n"
//				+ "emphasis\r\n"
//				+ "emphasize\r\n"
//				+ "employ\r\n"
//				+ "employee\r\n"
//				+ "employer\r\n"
//				+ "employment\r\n"
//				+ "empty\r\n"
//				+ "enable\r\n"
//				+ "encounter\r\n"
//				+ "encourage\r\n"
//				+ "end\r\n"
//				+ "enemy\r\n"
//				+ "energy\r\n"
//				+ "enforcement\r\n"
//				+ "engage\r\n"
//				+ "engine\r\n"
//				+ "engineer\r\n"
//				+ "engineering\r\n"
//				+ "English\r\n"
//				+ "enhance\r\n"
//				+ "enjoy\r\n"
//				+ "enormous\r\n"
//				+ "enough\r\n"
//				+ "ensure\r\n"
//				+ "enter\r\n"
//				+ "enterprise\r\n"
//				+ "entertainment\r\n"
//				+ "entire\r\n"
//				+ "entirely\r\n"
//				+ "entrance\r\n"
//				+ "entry\r\n"
//				+ "environment\r\n"
//				+ "environmental\r\n"
//				+ "episode\r\n"
//				+ "equal\r\n"
//				+ "equally\r\n"
//				+ "equipment\r\n"
//				+ "era\r\n"
//				+ "error\r\n"
//				+ "escape\r\n"
//				+ "especially\r\n"
//				+ "essay\r\n"
//				+ "essential\r\n"
//				+ "essentially\r\n"
//				+ "establish\r\n"
//				+ "establishment\r\n"
//				+ "estate\r\n"
//				+ "estimate\r\n"
//				+ "etc\r\n"
//				+ "ethics\r\n"
//				+ "ethnic\r\n"
//				+ "European\r\n"
//				+ "evaluate\r\n"
//				+ "evaluation\r\n"
//				+ "even\r\n"
//				+ "evening\r\n"
//				+ "event\r\n"
//				+ "eventually\r\n"
//				+ "ever\r\n"
//				+ "every\r\n"
//				+ "everybody\r\n"
//				+ "everyday\r\n"
//				+ "everyone\r\n"
//				+ "everything\r\n"
//				+ "everywhere\r\n"
//				+ "evidence\r\n"
//				+ "evolution\r\n"
//				+ "evolve\r\n"
//				+ "exact\r\n"
//				+ "exactly\r\n"
//				+ "examination\r\n"
//				+ "examine\r\n"
//				+ "example\r\n"
//				+ "exceed\r\n"
//				+ "excellent\r\n"
//				+ "except\r\n"
//				+ "exception\r\n"
//				+ "exchange\r\n"
//				+ "exciting\r\n"
//				+ "executive\r\n"
//				+ "exercise\r\n"
//				+ "exhibit\r\n"
//				+ "exhibition\r\n"
//				+ "exist\r\n"
//				+ "existence\r\n"
//				+ "existing\r\n"
//				+ "expand\r\n"
//				+ "expansion\r\n"
//				+ "expect\r\n"
//				+ "expectation\r\n"
//				+ "expense\r\n"
//				+ "expensive\r\n"
//				+ "experience\r\n"
//				+ "experiment\r\n"
//				+ "expert\r\n"
//				+ "explain\r\n"
//				+ "explanation\r\n"
//				+ "explode\r\n"
//				+ "explore\r\n"
//				+ "explosion\r\n"
//				+ "expose\r\n"
//				+ "exposure\r\n"
//				+ "express\r\n"
//				+ "expression\r\n"
//				+ "extend\r\n"
//				+ "extension\r\n"
//				+ "extensive\r\n"
//				+ "extent\r\n"
//				+ "external\r\n"
//				+ "extra\r\n"
//				+ "extraordinary\r\n"
//				+ "extreme\r\n"
//				+ "extremely\r\n"
//				+ "eye\r\n"
//				+ "fabric\r\n"
//				+ "face\r\n"
//				+ "facility\r\n"
//				+ "fact\r\n"
//				+ "factor\r\n"
//				+ "factory\r\n"
//				+ "faculty\r\n"
//				+ "fade\r\n"
//				+ "fail\r\n"
//				+ "failure\r\n"
//				+ "fair\r\n"
//				+ "fairly\r\n"
//				+ "faith\r\n"
//				+ "fall\r\n"
//				+ "false\r\n"
//				+ "familiar\r\n"
//				+ "family\r\n"
//				+ "famous\r\n"
//				+ "fan\r\n"
//				+ "fantasy\r\n"
//				+ "far\r\n"
//				+ "farm\r\n"
//				+ "farmer\r\n"
//				+ "fashion\r\n"
//				+ "fast\r\n"
//				+ "fat\r\n"
//				+ "fate\r\n"
//				+ "father\r\n"
//				+ "fault\r\n"
//				+ "favor\r\n"
//				+ "favorite\r\n"
//				+ "fear\r\n"
//				+ "feature\r\n"
//				+ "federal\r\n"
//				+ "fee\r\n"
//				+ "feed\r\n"
//				+ "feel\r\n"
//				+ "feeling\r\n"
//				+ "fellow\r\n"
//				+ "female\r\n"
//				+ "fence\r\n"
//				+ "few\r\n"
//				+ "fewer\r\n"
//				+ "fiber\r\n"
//				+ "fiction\r\n"
//				+ "field\r\n"
//				+ "fifteen\r\n"
//				+ "fifth\r\n"
//				+ "fifty\r\n"
//				+ "fight\r\n"
//				+ "fighter\r\n"
//				+ "fighting\r\n"
//				+ "figure\r\n"
//				+ "file\r\n"
//				+ "fill\r\n"
//				+ "film\r\n"
//				+ "final\r\n"
//				+ "finally\r\n"
//				+ "finance\r\n"
//				+ "financial\r\n"
//				+ "find\r\n"
//				+ "finding\r\n"
//				+ "fine\r\n"
//				+ "finger\r\n"
//				+ "finish\r\n"
//				+ "fire\r\n"
//				+ "firm\r\n"
//				+ "first\r\n"
//				+ "fish\r\n"
//				+ "fishing\r\n"
//				+ "fit\r\n"
//				+ "fitness\r\n"
//				+ "five\r\n"
//				+ "fix\r\n"
//				+ "flag\r\n"
//				+ "flame\r\n"
//				+ "flat\r\n"
//				+ "flavor\r\n"
//				+ "flee\r\n"
//				+ "flesh\r\n"
//				+ "flight\r\n"
//				+ "float\r\n"
//				+ "floor\r\n"
//				+ "flow\r\n"
//				+ "flower\r\n"
//				+ "fly\r\n"
//				+ "focus\r\n"
//				+ "folk\r\n"
//				+ "follow\r\n"
//				+ "following\r\n"
//				+ "food\r\n"
//				+ "foot\r\n"
//				+ "football\r\n"
//				+ "for\r\n"
//				+ "force\r\n"
//				+ "foreign\r\n"
//				+ "forest\r\n"
//				+ "forever\r\n"
//				+ "forget\r\n"
//				+ "form\r\n"
//				+ "formal\r\n"
//				+ "formation\r\n"
//				+ "former\r\n"
//				+ "formula\r\n"
//				+ "forth\r\n"
//				+ "fortune\r\n"
//				+ "forward\r\n"
//				+ "found\r\n"
//				+ "foundation\r\n"
//				+ "founder\r\n"
//				+ "four\r\n"
//				+ "fourth\r\n"
//				+ "frame\r\n"
//				+ "framework\r\n"
//				+ "free\r\n"
//				+ "freedom\r\n"
//				+ "freeze\r\n"
//				+ "French\r\n"
//				+ "frequency\r\n"
//				+ "frequent\r\n"
//				+ "frequently\r\n"
//				+ "fresh\r\n"
//				+ "friend\r\n"
//				+ "friendly\r\n"
//				+ "friendship\r\n"
//				+ "from\r\n"
//				+ "front\r\n"
//				+ "fruit\r\n"
//				+ "frustration\r\n"
//				+ "fuel\r\n"
//				+ "full\r\n"
//				+ "fully\r\n"
//				+ "fun\r\n"
//				+ "function\r\n"
//				+ "fund\r\n"
//				+ "fundamental\r\n"
//				+ "funding\r\n"
//				+ "funeral\r\n"
//				+ "funny\r\n"
//				+ "furniture\r\n"
//				+ "furthermore\r\n"
//				+ "future\r\n"
//				+ "gain\r\n"
//				+ "galaxy\r\n"
//				+ "gallery\r\n"
//				+ "game\r\n"
//				+ "gang\r\n"
//				+ "gap\r\n"
//				+ "garage\r\n"
//				+ "garden\r\n"
//				+ "garlic\r\n"
//				+ "gas\r\n"
//				+ "gate\r\n"
//				+ "gather\r\n"
//				+ "gay\r\n"
//				+ "gaze\r\n"
//				+ "gear\r\n"
//				+ "gender\r\n"
//				+ "gene\r\n"
//				+ "general\r\n"
//				+ "generally\r\n"
//				+ "generate\r\n"
//				+ "generation\r\n"
//				+ "genetic\r\n"
//				+ "gentleman\r\n"
//				+ "gently\r\n"
//				+ "German\r\n"
//				+ "gesture\r\n"
//				+ "get\r\n"
//				+ "ghost\r\n"
//				+ "giant\r\n"
//				+ "gift\r\n"
//				+ "gifted\r\n"
//				+ "girl\r\n"
//				+ "girlfriend\r\n"
//				+ "give\r\n"
//				+ "given\r\n"
//				+ "glad\r\n"
//				+ "glance\r\n"
//				+ "glass\r\n"
//				+ "global\r\n"
//				+ "glove\r\n"
//				+ "go\r\n"
//				+ "goal\r\n"
//				+ "God\r\n"
//				+ "gold\r\n"
//				+ "golden\r\n"
//				+ "golf\r\n"
//				+ "good\r\n"
//				+ "government\r\n"
//				+ "governor\r\n"
//				+ "grab\r\n"
//				+ "grade\r\n"
//				+ "gradually\r\n"
//				+ "graduate\r\n"
//				+ "grain\r\n"
//				+ "grand\r\n"
//				+ "grandfather\r\n"
//				+ "grandmother\r\n"
//				+ "grant\r\n"
//				+ "grass\r\n"
//				+ "grave\r\n"
//				+ "gray\r\n"
//				+ "great\r\n"
//				+ "greatest\r\n"
//				+ "green\r\n"
//				+ "grocery\r\n"
//				+ "ground\r\n"
//				+ "group\r\n"
//				+ "grow\r\n"
//				+ "growing\r\n"
//				+ "growth\r\n"
//				+ "guarantee\r\n"
//				+ "guard\r\n"
//				+ "guess\r\n"
//				+ "guest\r\n"
//				+ "guide\r\n"
//				+ "guideline\r\n"
//				+ "guilty\r\n"
//				+ "gun\r\n"
//				+ "guy\r\n"
//				+ "habit\r\n"
//				+ "habitat\r\n"
//				+ "hair\r\n"
//				+ "half\r\n"
//				+ "hall\r\n"
//				+ "hand\r\n"
//				+ "handful\r\n"
//				+ "handle\r\n"
//				+ "hang\r\n"
//				+ "happen\r\n"
//				+ "happy\r\n"
//				+ "hard\r\n"
//				+ "hardly\r\n"
//				+ "hat\r\n"
//				+ "hate\r\n"
//				+ "have\r\n"
//				+ "he\r\n"
//				+ "head\r\n"
//				+ "headline\r\n"
//				+ "headquarters\r\n"
//				+ "health\r\n"
//				+ "healthy\r\n"
//				+ "hear\r\n"
//				+ "hearing\r\n"
//				+ "heart\r\n"
//				+ "heat\r\n"
//				+ "heaven\r\n"
//				+ "heavily\r\n"
//				+ "heavy\r\n"
//				+ "heel\r\n"
//				+ "height\r\n"
//				+ "helicopter\r\n"
//				+ "hell\r\n"
//				+ "hello\r\n"
//				+ "help\r\n"
//				+ "helpful\r\n"
//				+ "her\r\n"
//				+ "here\r\n"
//				+ "heritage\r\n"
//				+ "hero\r\n"
//				+ "herself\r\n"
//				+ "hey\r\n"
//				+ "hi\r\n"
//				+ "hide\r\n"
//				+ "high\r\n"
//				+ "highlight\r\n"
//				+ "highly\r\n"
//				+ "highway\r\n"
//				+ "hill\r\n"
//				+ "him\r\n"
//				+ "himself\r\n"
//				+ "hip\r\n"
//				+ "hire\r\n"
//				+ "his\r\n"
//				+ "historian\r\n"
//				+ "historic\r\n"
//				+ "historical\r\n"
//				+ "history\r\n"
//				+ "hit\r\n"
//				+ "hold\r\n"
//				+ "hole\r\n"
//				+ "holiday\r\n"
//				+ "holy\r\n"
//				+ "home\r\n"
//				+ "homeless\r\n"
//				+ "honest\r\n"
//				+ "honey\r\n"
//				+ "honor\r\n"
//				+ "hope\r\n"
//				+ "horizon\r\n"
//				+ "horror\r\n"
//				+ "horse\r\n"
//				+ "hospital\r\n"
//				+ "host\r\n"
//				+ "hot\r\n"
//				+ "hotel\r\n"
//				+ "hour\r\n"
//				+ "house\r\n"
//				+ "household\r\n"
//				+ "housing\r\n"
//				+ "how\r\n"
//				+ "however\r\n"
//				+ "huge\r\n"
//				+ "human\r\n"
//				+ "humor\r\n"
//				+ "hundred\r\n"
//				+ "hungry\r\n"
//				+ "hunter\r\n"
//				+ "hunting\r\n"
//				+ "hurt\r\n"
//				+ "husband\r\n"
//				+ "hypothesis\r\n"
//				+ "I\r\n"
//				+ "ice\r\n"
//				+ "idea\r\n"
//				+ "ideal\r\n"
//				+ "identification\r\n"
//				+ "identify\r\n"
//				+ "identity\r\n"
//				+ "ie\r\n"
//				+ "if\r\n"
//				+ "ignore\r\n"
//				+ "ill\r\n"
//				+ "illegal\r\n"
//				+ "illness\r\n"
//				+ "illustrate\r\n"
//				+ "image\r\n"
//				+ "imagination\r\n"
//				+ "imagine\r\n"
//				+ "immediate\r\n"
//				+ "immediately\r\n"
//				+ "immigrant\r\n"
//				+ "immigration\r\n"
//				+ "impact\r\n"
//				+ "implement\r\n"
//				+ "implication\r\n"
//				+ "imply\r\n"
//				+ "importance\r\n"
//				+ "important\r\n"
//				+ "impose\r\n"
//				+ "impossible\r\n"
//				+ "impress\r\n"
//				+ "impression\r\n"
//				+ "impressive\r\n"
//				+ "improve\r\n"
//				+ "improvement\r\n"
//				+ "in\r\n"
//				+ "incentive\r\n"
//				+ "incident\r\n"
//				+ "include\r\n"
//				+ "including\r\n"
//				+ "income\r\n"
//				+ "incorporate\r\n"
//				+ "increase\r\n"
//				+ "increased\r\n"
//				+ "increasing\r\n"
//				+ "increasingly\r\n"
//				+ "incredible\r\n"
//				+ "indeed\r\n"
//				+ "independence\r\n"
//				+ "independent\r\n"
//				+ "index\r\n"
//				+ "Indian\r\n"
//				+ "indicate\r\n"
//				+ "indication\r\n"
//				+ "individual\r\n"
//				+ "industrial\r\n"
//				+ "industry\r\n"
//				+ "infant\r\n"
//				+ "infection\r\n"
//				+ "inflation\r\n"
//				+ "influence\r\n"
//				+ "inform\r\n"
//				+ "information\r\n"
//				+ "ingredient\r\n"
//				+ "initial\r\n"
//				+ "initially\r\n"
//				+ "initiative\r\n"
//				+ "injury\r\n"
//				+ "inner\r\n"
//				+ "innocent\r\n"
//				+ "inquiry\r\n"
//				+ "inside\r\n"
//				+ "insight\r\n"
//				+ "insist\r\n"
//				+ "inspire\r\n"
//				+ "install\r\n"
//				+ "instance\r\n"
//				+ "instead\r\n"
//				+ "institution\r\n"
//				+ "institutional\r\n"
//				+ "instruction\r\n"
//				+ "instructor\r\n"
//				+ "instrument\r\n"
//				+ "insurance\r\n"
//				+ "intellectual\r\n"
//				+ "intelligence\r\n"
//				+ "intend\r\n"
//				+ "intense\r\n"
//				+ "intensity\r\n"
//				+ "intention\r\n"
//				+ "interaction\r\n"
//				+ "interest\r\n"
//				+ "interested\r\n"
//				+ "interesting\r\n"
//				+ "internal\r\n"
//				+ "international\r\n"
//				+ "Internet\r\n"
//				+ "interpret\r\n"
//				+ "interpretation\r\n"
//				+ "intervention\r\n"
//				+ "interview\r\n"
//				+ "into\r\n"
//				+ "introduce\r\n"
//				+ "introduction\r\n"
//				+ "invasion\r\n"
//				+ "invest\r\n"
//				+ "investigate\r\n"
//				+ "investigation\r\n"
//				+ "investigator\r\n"
//				+ "investment\r\n"
//				+ "investor\r\n"
//				+ "invite\r\n"
//				+ "involve\r\n"
//				+ "involved\r\n"
//				+ "involvement\r\n"
//				+ "Iraqi\r\n"
//				+ "Irish\r\n"
//				+ "iron\r\n"
//				+ "Islamic\r\n"
//				+ "island\r\n"
//				+ "Israeli\r\n"
//				+ "issue\r\n"
//				+ "it\r\n"
//				+ "Italian\r\n"
//				+ "item\r\n"
//				+ "its\r\n"
//				+ "itself\r\n"
//				+ "jacket\r\n"
//				+ "jail\r\n"
//				+ "Japanese\r\n"
//				+ "jet\r\n"
//				+ "Jew\r\n"
//				+ "Jewish\r\n"
//				+ "job\r\n"
//				+ "join\r\n"
//				+ "joint\r\n"
//				+ "joke\r\n"
//				+ "journal\r\n"
//				+ "journalist\r\n"
//				+ "journey\r\n"
//				+ "joy\r\n"
//				+ "judge\r\n"
//				+ "judgment\r\n"
//				+ "juice\r\n"
//				+ "jump\r\n"
//				+ "junior\r\n"
//				+ "jury\r\n"
//				+ "just\r\n"
//				+ "justice\r\n"
//				+ "justify\r\n"
//				+ "keep\r\n"
//				+ "key\r\n"
//				+ "kick\r\n"
//				+ "kid\r\n"
//				+ "kill\r\n"
//				+ "killer\r\n"
//				+ "killing\r\n"
//				+ "kind\r\n"
//				+ "king\r\n"
//				+ "kiss\r\n"
//				+ "kitchen\r\n"
//				+ "knee\r\n"
//				+ "knife\r\n"
//				+ "knock\r\n"
//				+ "know\r\n"
//				+ "knowledge\r\n"
//				+ "lab\r\n"
//				+ "label\r\n"
//				+ "labor\r\n"
//				+ "laboratory\r\n"
//				+ "lack\r\n"
//				+ "lady\r\n"
//				+ "lake\r\n"
//				+ "land\r\n"
//				+ "landscape\r\n"
//				+ "language\r\n"
//				+ "lap\r\n"
//				+ "large\r\n"
//				+ "largely\r\n"
//				+ "last\r\n"
//				+ "late\r\n"
//				+ "later\r\n"
//				+ "Latin\r\n"
//				+ "latter\r\n"
//				+ "laugh\r\n"
//				+ "launch\r\n"
//				+ "law\r\n"
//				+ "lawn\r\n"
//				+ "lawsuit\r\n"
//				+ "lawyer\r\n"
//				+ "lay\r\n"
//				+ "layer\r\n"
//				+ "lead\r\n"
//				+ "leader\r\n"
//				+ "leadership\r\n"
//				+ "leading\r\n"
//				+ "leaf\r\n"
//				+ "league\r\n"
//				+ "lean\r\n"
//				+ "learn\r\n"
//				+ "learning\r\n"
//				+ "least\r\n"
//				+ "leather\r\n"
//				+ "leave\r\n"
//				+ "left\r\n"
//				+ "leg\r\n"
//				+ "legacy\r\n"
//				+ "legal\r\n"
//				+ "legend\r\n"
//				+ "legislation\r\n"
//				+ "legitimate\r\n"
//				+ "lemon\r\n"
//				+ "length\r\n"
//				+ "less\r\n"
//				+ "lesson\r\n"
//				+ "let\r\n"
//				+ "letter\r\n"
//				+ "level\r\n"
//				+ "liberal\r\n"
//				+ "library\r\n"
//				+ "license\r\n"
//				+ "lie\r\n"
//				+ "life\r\n"
//				+ "lifestyle\r\n"
//				+ "lifetime\r\n"
//				+ "lift\r\n"
//				+ "light\r\n"
//				+ "like\r\n"
//				+ "likely\r\n"
//				+ "limit\r\n"
//				+ "limitation\r\n"
//				+ "limited\r\n"
//				+ "line\r\n"
//				+ "link\r\n"
//				+ "lip\r\n"
//				+ "list\r\n"
//				+ "listen\r\n"
//				+ "literally\r\n"
//				+ "literary\r\n"
//				+ "literature\r\n"
//				+ "little\r\n"
//				+ "live\r\n"
//				+ "living\r\n"
//				+ "load\r\n"
//				+ "loan\r\n"
//				+ "local\r\n"
//				+ "locate\r\n"
//				+ "location\r\n"
//				+ "lock\r\n"
//				+ "long\r\n"
//				+ "long-term\r\n"
//				+ "look\r\n"
//				+ "loose\r\n"
//				+ "lose\r\n"
//				+ "loss\r\n"
//				+ "lost\r\n"
//				+ "lot\r\n"
//				+ "lots\r\n"
//				+ "loud\r\n"
//				+ "love\r\n"
//				+ "lovely\r\n"
//				+ "lover\r\n"
//				+ "low\r\n"
//				+ "lower\r\n"
//				+ "luck\r\n"
//				+ "lucky\r\n"
//				+ "lunch\r\n"
//				+ "lung\r\n"
//				+ "machine\r\n"
//				+ "mad\r\n"
//				+ "magazine\r\n"
//				+ "mail\r\n"
//				+ "main\r\n"
//				+ "mainly\r\n"
//				+ "maintain\r\n"
//				+ "maintenance\r\n"
//				+ "major\r\n"
//				+ "majority\r\n"
//				+ "make\r\n"
//				+ "maker\r\n"
//				+ "makeup\r\n"
//				+ "male\r\n"
//				+ "mall\r\n"
//				+ "man\r\n"
//				+ "manage\r\n"
//				+ "management\r\n"
//				+ "manager\r\n"
//				+ "manner\r\n"
//				+ "manufacturer\r\n"
//				+ "manufacturing\r\n"
//				+ "many\r\n"
//				+ "map\r\n"
//				+ "margin\r\n"
//				+ "mark\r\n"
//				+ "market\r\n"
//				+ "marketing\r\n"
//				+ "marriage\r\n"
//				+ "married\r\n"
//				+ "marry\r\n"
//				+ "mask\r\n"
//				+ "mass\r\n"
//				+ "massive\r\n"
//				+ "master\r\n"
//				+ "match\r\n"
//				+ "material\r\n"
//				+ "math\r\n"
//				+ "matter\r\n"
//				+ "may\r\n"
//				+ "maybe\r\n"
//				+ "mayor\r\n"
//				+ "me\r\n"
//				+ "meal\r\n"
//				+ "mean\r\n"
//				+ "meaning\r\n"
//				+ "meanwhile\r\n"
//				+ "measure\r\n"
//				+ "measurement\r\n"
//				+ "meat\r\n"
//				+ "mechanism\r\n"
//				+ "media\r\n"
//				+ "medical\r\n"
//				+ "medication\r\n"
//				+ "medicine\r\n"
//				+ "medium\r\n"
//				+ "meet\r\n"
//				+ "meeting\r\n"
//				+ "member\r\n"
//				+ "membership\r\n"
//				+ "memory\r\n"
//				+ "mental\r\n"
//				+ "mention\r\n"
//				+ "menu\r\n"
//				+ "mere\r\n"
//				+ "merely\r\n"
//				+ "mess\r\n"
//				+ "message\r\n"
//				+ "metal\r\n"
//				+ "meter\r\n"
//				+ "method\r\n"
//				+ "Mexican\r\n"
//				+ "middle\r\n"
//				+ "might\r\n"
//				+ "military\r\n"
//				+ "milk\r\n"
//				+ "million\r\n"
//				+ "mind\r\n"
//				+ "mine\r\n"
//				+ "minister\r\n"
//				+ "minor\r\n"
//				+ "minority\r\n"
//				+ "minute\r\n"
//				+ "miracle\r\n"
//				+ "mirror\r\n"
//				+ "miss\r\n"
//				+ "missile\r\n"
//				+ "mission\r\n"
//				+ "mistake\r\n"
//				+ "mix\r\n"
//				+ "mixture\r\n"
//				+ "mm-hmm\r\n"
//				+ "mode\r\n"
//				+ "model\r\n"
//				+ "moderate\r\n"
//				+ "modern\r\n"
//				+ "modest\r\n"
//				+ "mom\r\n"
//				+ "moment\r\n"
//				+ "money\r\n"
//				+ "monitor\r\n"
//				+ "month\r\n"
//				+ "mood\r\n"
//				+ "moon\r\n"
//				+ "moral\r\n"
//				+ "more\r\n"
//				+ "moreover\r\n"
//				+ "morning\r\n"
//				+ "mortgage\r\n"
//				+ "most\r\n"
//				+ "mostly\r\n"
//				+ "mother\r\n"
//				+ "motion\r\n"
//				+ "motivation\r\n"
//				+ "motor\r\n"
//				+ "mount\r\n"
//				+ "mountain\r\n"
//				+ "mouse\r\n"
//				+ "mouth\r\n"
//				+ "move\r\n"
//				+ "movement\r\n"
//				+ "movie\r\n"
//				+ "Mr\r\n"
//				+ "Mrs\r\n"
//				+ "Ms\r\n"
//				+ "much\r\n"
//				+ "multiple\r\n"
//				+ "murder\r\n"
//				+ "muscle\r\n"
//				+ "museum\r\n"
//				+ "music\r\n"
//				+ "musical\r\n"
//				+ "musician\r\n"
//				+ "Muslim\r\n"
//				+ "must\r\n"
//				+ "mutual\r\n"
//				+ "my\r\n"
//				+ "myself\r\n"
//				+ "mystery\r\n"
//				+ "myth\r\n"
//				+ "naked\r\n"
//				+ "name\r\n"
//				+ "narrative\r\n"
//				+ "narrow\r\n"
//				+ "nation\r\n"
//				+ "national\r\n"
//				+ "native\r\n"
//				+ "natural\r\n"
//				+ "naturally\r\n"
//				+ "nature\r\n"
//				+ "near\r\n"
//				+ "nearby\r\n"
//				+ "nearly\r\n"
//				+ "necessarily\r\n"
//				+ "necessary\r\n"
//				+ "neck\r\n"
//				+ "need\r\n"
//				+ "negative\r\n"
//				+ "negotiate\r\n"
//				+ "negotiation\r\n"
//				+ "neighbor\r\n"
//				+ "neighborhood\r\n"
//				+ "neither\r\n"
//				+ "nerve\r\n"
//				+ "nervous\r\n"
//				+ "net\r\n"
//				+ "network\r\n"
//				+ "never\r\n"
//				+ "nevertheless\r\n"
//				+ "new\r\n"
//				+ "newly\r\n"
//				+ "news\r\n"
//				+ "newspaper\r\n"
//				+ "next\r\n"
//				+ "nice\r\n"
//				+ "night\r\n"
//				+ "nine\r\n"
//				+ "no\r\n"
//				+ "nobody\r\n"
//				+ "nod\r\n"
//				+ "noise\r\n"
//				+ "nomination\r\n"
//				+ "none\r\n"
//				+ "nonetheless\r\n"
//				+ "nor\r\n"
//				+ "normal\r\n"
//				+ "normally\r\n"
//				+ "north\r\n"
//				+ "northern\r\n"
//				+ "nose\r\n"
//				+ "not\r\n"
//				+ "note\r\n"
//				+ "nothing\r\n"
//				+ "notice\r\n"
//				+ "notion\r\n"
//				+ "novel\r\n"
//				+ "now\r\n"
//				+ "nowhere\r\n"
//				+ "n't\r\n"
//				+ "nuclear\r\n"
//				+ "number\r\n"
//				+ "numerous\r\n"
//				+ "nurse\r\n"
//				+ "nut\r\n"
//				+ "object\r\n"
//				+ "objective\r\n"
//				+ "obligation\r\n"
//				+ "observation\r\n"
//				+ "observe\r\n"
//				+ "observer\r\n"
//				+ "obtain\r\n"
//				+ "obvious\r\n"
//				+ "obviously\r\n"
//				+ "occasion\r\n"
//				+ "occasionally\r\n"
//				+ "occupation\r\n"
//				+ "occupy\r\n"
//				+ "occur\r\n"
//				+ "ocean\r\n"
//				+ "odd\r\n"
//				+ "odds\r\n"
//				+ "of\r\n"
//				+ "off\r\n"
//				+ "offense\r\n"
//				+ "offensive\r\n"
//				+ "offer\r\n"
//				+ "office\r\n"
//				+ "officer\r\n"
//				+ "official\r\n"
//				+ "often\r\n"
//				+ "oh\r\n"
//				+ "oil\r\n"
//				+ "ok\r\n"
//				+ "okay\r\n"
//				+ "old\r\n"
//				+ "Olympic\r\n"
//				+ "on\r\n"
//				+ "once\r\n"
//				+ "one\r\n"
//				+ "ongoing\r\n"
//				+ "onion\r\n"
//				+ "online\r\n"
//				+ "only\r\n"
//				+ "onto\r\n"
//				+ "open\r\n"
//				+ "opening\r\n"
//				+ "operate\r\n"
//				+ "operating\r\n"
//				+ "operation\r\n"
//				+ "operator\r\n"
//				+ "opinion\r\n"
//				+ "opponent\r\n"
//				+ "opportunity\r\n"
//				+ "oppose\r\n"
//				+ "opposite\r\n"
//				+ "opposition\r\n"
//				+ "option\r\n"
//				+ "or\r\n"
//				+ "orange\r\n"
//				+ "order\r\n"
//				+ "ordinary\r\n"
//				+ "organic\r\n"
//				+ "organization\r\n"
//				+ "organize\r\n"
//				+ "orientation\r\n"
//				+ "origin\r\n"
//				+ "original\r\n"
//				+ "originally\r\n"
//				+ "other\r\n"
//				+ "others\r\n"
//				+ "otherwise\r\n"
//				+ "ought\r\n"
//				+ "our\r\n"
//				+ "ourselves\r\n"
//				+ "out\r\n"
//				+ "outcome\r\n"
//				+ "outside\r\n"
//				+ "oven\r\n"
//				+ "over\r\n"
//				+ "overall\r\n"
//				+ "overcome\r\n"
//				+ "overlook\r\n"
//				+ "owe\r\n"
//				+ "own\r\n"
//				+ "owner\r\n"
//				+ "pace\r\n"
//				+ "pack\r\n"
//				+ "package\r\n"
//				+ "page\r\n"
//				+ "pain\r\n"
//				+ "painful\r\n"
//				+ "paint\r\n"
//				+ "painter\r\n"
//				+ "painting\r\n"
//				+ "pair\r\n"
//				+ "pale\r\n"
//				+ "Palestinian\r\n"
//				+ "palm\r\n"
//				+ "pan\r\n"
//				+ "panel\r\n"
//				+ "pant\r\n"
//				+ "paper\r\n"
//				+ "parent\r\n"
//				+ "park\r\n"
//				+ "parking\r\n"
//				+ "part\r\n"
//				+ "participant\r\n"
//				+ "participate\r\n"
//				+ "participation\r\n"
//				+ "particular\r\n"
//				+ "particularly\r\n"
//				+ "partly\r\n"
//				+ "partner\r\n"
//				+ "partnership\r\n"
//				+ "party\r\n"
//				+ "pass\r\n"
//				+ "passage\r\n"
//				+ "passenger\r\n"
//				+ "passion\r\n"
//				+ "past\r\n"
//				+ "patch\r\n"
//				+ "path\r\n"
//				+ "patient\r\n"
//				+ "pattern\r\n"
//				+ "pause\r\n"
//				+ "pay\r\n"
//				+ "payment\r\n"
//				+ "PC\r\n"
//				+ "peace\r\n"
//				+ "peak\r\n"
//				+ "peer\r\n"
//				+ "penalty\r\n"
//				+ "people\r\n"
//				+ "pepper\r\n"
//				+ "per\r\n"
//				+ "perceive\r\n"
//				+ "percentage\r\n"
//				+ "perception\r\n"
//				+ "perfect\r\n"
//				+ "perfectly\r\n"
//				+ "perform\r\n"
//				+ "performance\r\n"
//				+ "perhaps\r\n"
//				+ "period\r\n"
//				+ "permanent\r\n"
//				+ "permission\r\n"
//				+ "permit\r\n"
//				+ "person\r\n"
//				+ "personal\r\n"
//				+ "personality\r\n"
//				+ "personally\r\n"
//				+ "personnel\r\n"
//				+ "perspective\r\n"
//				+ "persuade\r\n"
//				+ "pet\r\n"
//				+ "phase\r\n"
//				+ "phenomenon\r\n"
//				+ "philosophy\r\n"
//				+ "phone\r\n"
//				+ "photo\r\n"
//				+ "photograph\r\n"
//				+ "photographer\r\n"
//				+ "phrase\r\n"
//				+ "physical\r\n"
//				+ "physically\r\n"
//				+ "physician\r\n"
//				+ "piano\r\n"
//				+ "pick\r\n"
//				+ "picture\r\n"
//				+ "pie\r\n"
//				+ "piece\r\n"
//				+ "pile\r\n"
//				+ "pilot\r\n"
//				+ "pine\r\n"
//				+ "pink\r\n"
//				+ "pipe\r\n"
//				+ "pitch\r\n"
//				+ "place\r\n"
//				+ "plan\r\n"
//				+ "plane\r\n"
//				+ "planet\r\n"
//				+ "planning\r\n"
//				+ "plant\r\n"
//				+ "plastic\r\n"
//				+ "plate\r\n"
//				+ "platform\r\n"
//				+ "play\r\n"
//				+ "player\r\n"
//				+ "please\r\n"
//				+ "pleasure\r\n"
//				+ "plenty\r\n"
//				+ "plot\r\n"
//				+ "plus\r\n"
//				+ "PM\r\n"
//				+ "pocket\r\n"
//				+ "poem\r\n"
//				+ "poet\r\n"
//				+ "poetry\r\n"
//				+ "point\r\n"
//				+ "pole\r\n"
//				+ "police\r\n"
//				+ "policy\r\n"
//				+ "political\r\n"
//				+ "politically\r\n"
//				+ "politician\r\n"
//				+ "politics\r\n"
//				+ "poll\r\n"
//				+ "pollution\r\n"
//				+ "pool\r\n"
//				+ "poor\r\n"
//				+ "pop\r\n"
//				+ "popular\r\n"
//				+ "population\r\n"
//				+ "porch\r\n"
//				+ "port\r\n"
//				+ "portion\r\n"
//				+ "portrait\r\n"
//				+ "portray\r\n"
//				+ "pose\r\n"
//				+ "position\r\n"
//				+ "positive\r\n"
//				+ "possess\r\n"
//				+ "possibility\r\n"
//				+ "possible\r\n"
//				+ "possibly\r\n"
//				+ "post\r\n"
//				+ "pot\r\n"
//				+ "potato\r\n"
//				+ "potential\r\n"
//				+ "potentially\r\n"
//				+ "pound\r\n"
//				+ "pour\r\n"
//				+ "poverty\r\n"
//				+ "powder\r\n"
//				+ "power\r\n"
//				+ "powerful\r\n"
//				+ "practical\r\n"
//				+ "practice\r\n"
//				+ "pray\r\n"
//				+ "prayer\r\n"
//				+ "precisely\r\n"
//				+ "predict\r\n"
//				+ "prefer\r\n"
//				+ "preference\r\n"
//				+ "pregnancy\r\n"
//				+ "pregnant\r\n"
//				+ "preparation\r\n"
//				+ "prepare\r\n"
//				+ "prescription\r\n"
//				+ "presence\r\n"
//				+ "present\r\n"
//				+ "presentation\r\n"
//				+ "preserve\r\n"
//				+ "president\r\n"
//				+ "presidential\r\n"
//				+ "press\r\n"
//				+ "pressure\r\n"
//				+ "pretend\r\n"
//				+ "pretty\r\n"
//				+ "prevent\r\n"
//				+ "previous\r\n"
//				+ "previously\r\n"
//				+ "price\r\n"
//				+ "pride\r\n"
//				+ "priest\r\n"
//				+ "primarily\r\n"
//				+ "primary\r\n"
//				+ "prime\r\n"
//				+ "principal\r\n"
//				+ "principle\r\n"
//				+ "print\r\n"
//				+ "prior\r\n"
//				+ "priority\r\n"
//				+ "prison\r\n"
//				+ "prisoner\r\n"
//				+ "privacy\r\n"
//				+ "private\r\n"
//				+ "probably\r\n"
//				+ "problem\r\n"
//				+ "procedure\r\n"
//				+ "proceed\r\n"
//				+ "process\r\n"
//				+ "produce\r\n"
//				+ "producer\r\n"
//				+ "product\r\n"
//				+ "production\r\n"
//				+ "profession\r\n"
//				+ "professional\r\n"
//				+ "professor\r\n"
//				+ "profile\r\n"
//				+ "profit\r\n"
//				+ "program\r\n"
//				+ "progress\r\n"
//				+ "project\r\n"
//				+ "prominent\r\n"
//				+ "promise\r\n"
//				+ "promote\r\n"
//				+ "prompt\r\n"
//				+ "proof\r\n"
//				+ "proper\r\n"
//				+ "properly\r\n"
//				+ "property\r\n"
//				+ "proportion\r\n"
//				+ "proposal\r\n"
//				+ "propose\r\n"
//				+ "proposed\r\n"
//				+ "prosecutor\r\n"
//				+ "prospect\r\n"
//				+ "protect\r\n"
//				+ "protection\r\n"
//				+ "protein\r\n"
//				+ "protest\r\n"
//				+ "proud\r\n"
//				+ "prove\r\n"
//				+ "provide\r\n"
//				+ "provider\r\n"
//				+ "province\r\n"
//				+ "provision\r\n"
//				+ "psychological\r\n"
//				+ "psychologist\r\n"
//				+ "psychology\r\n"
//				+ "public\r\n"
//				+ "publication\r\n"
//				+ "publicly\r\n"
//				+ "publish\r\n"
//				+ "publisher\r\n"
//				+ "pull\r\n"
//				+ "punishment\r\n"
//				+ "purchase\r\n"
//				+ "pure\r\n"
//				+ "purpose\r\n"
//				+ "pursue\r\n"
//				+ "push\r\n"
//				+ "put\r\n"
//				+ "qualify\r\n"
//				+ "quality\r\n"
//				+ "quarter\r\n"
//				+ "quarterback\r\n"
//				+ "question\r\n"
//				+ "quick\r\n"
//				+ "quickly\r\n"
//				+ "quiet\r\n"
//				+ "quietly\r\n"
//				+ "quit\r\n"
//				+ "quite\r\n"
//				+ "quote\r\n"
//				+ "race\r\n"
//				+ "racial\r\n"
//				+ "radical\r\n"
//				+ "radio\r\n"
//				+ "rail\r\n"
//				+ "rain\r\n"
//				+ "raise\r\n"
//				+ "range\r\n"
//				+ "rank\r\n"
//				+ "rapid\r\n"
//				+ "rapidly\r\n"
//				+ "rare\r\n"
//				+ "rarely\r\n"
//				+ "rate\r\n"
//				+ "rather\r\n"
//				+ "rating\r\n"
//				+ "ratio\r\n"
//				+ "raw\r\n"
//				+ "reach\r\n"
//				+ "react\r\n"
//				+ "reaction\r\n"
//				+ "read\r\n"
//				+ "reader\r\n"
//				+ "reading\r\n"
//				+ "ready\r\n"
//				+ "real\r\n"
//				+ "reality\r\n"
//				+ "realize\r\n"
//				+ "really\r\n"
//				+ "reason\r\n"
//				+ "reasonable\r\n"
//				+ "recall\r\n"
//				+ "receive\r\n"
//				+ "recent\r\n"
//				+ "recently\r\n"
//				+ "recipe\r\n"
//				+ "recognition\r\n"
//				+ "recognize\r\n"
//				+ "recommend\r\n"
//				+ "recommendation\r\n"
//				+ "record\r\n"
//				+ "recording\r\n"
//				+ "recover\r\n"
//				+ "recovery\r\n"
//				+ "recruit\r\n"
//				+ "red\r\n"
//				+ "reduce\r\n"
//				+ "reduction\r\n"
//				+ "refer\r\n"
//				+ "reference\r\n"
//				+ "reflect\r\n"
//				+ "reflection\r\n"
//				+ "reform\r\n"
//				+ "refugee\r\n"
//				+ "refuse\r\n"
//				+ "regard\r\n"
//				+ "regarding\r\n"
//				+ "regardless\r\n"
//				+ "regime\r\n"
//				+ "region\r\n"
//				+ "regional\r\n"
//				+ "register\r\n"
//				+ "regular\r\n"
//				+ "regularly\r\n"
//				+ "regulate\r\n"
//				+ "regulation\r\n"
//				+ "reinforce\r\n"
//				+ "reject\r\n"
//				+ "relate\r\n"
//				+ "relation\r\n"
//				+ "relationship\r\n"
//				+ "relative\r\n"
//				+ "relatively\r\n"
//				+ "relax\r\n"
//				+ "release\r\n"
//				+ "relevant\r\n"
//				+ "relief\r\n"
//				+ "religion\r\n"
//				+ "religious\r\n"
//				+ "rely\r\n"
//				+ "remain\r\n"
//				+ "remaining\r\n"
//				+ "remarkable\r\n"
//				+ "remember\r\n"
//				+ "remind\r\n"
//				+ "remote\r\n"
//				+ "remove\r\n"
//				+ "repeat\r\n"
//				+ "repeatedly\r\n"
//				+ "replace\r\n"
//				+ "reply\r\n"
//				+ "report\r\n"
//				+ "reporter\r\n"
//				+ "represent\r\n"
//				+ "representation\r\n"
//				+ "representative\r\n"
//				+ "Republican\r\n"
//				+ "reputation\r\n"
//				+ "request\r\n"
//				+ "require\r\n"
//				+ "requirement\r\n"
//				+ "research\r\n"
//				+ "researcher\r\n"
//				+ "resemble\r\n"
//				+ "reservation\r\n"
//				+ "resident\r\n"
//				+ "resist\r\n"
//				+ "resistance\r\n"
//				+ "resolution\r\n"
//				+ "resolve\r\n"
//				+ "resort\r\n"
//				+ "resource\r\n"
//				+ "respect\r\n"
//				+ "respond\r\n"
//				+ "respondent\r\n"
//				+ "response\r\n"
//				+ "responsibility\r\n"
//				+ "responsible\r\n"
//				+ "rest\r\n"
//				+ "restaurant\r\n"
//				+ "restore\r\n"
//				+ "restriction\r\n"
//				+ "result\r\n"
//				+ "retain\r\n"
//				+ "retire\r\n"
//				+ "retirement\r\n"
//				+ "return\r\n"
//				+ "reveal\r\n"
//				+ "revenue\r\n"
//				+ "review\r\n"
//				+ "revolution\r\n"
//				+ "rhythm\r\n"
//				+ "rice\r\n"
//				+ "rich\r\n"
//				+ "rid\r\n"
//				+ "ride\r\n"
//				+ "rifle\r\n"
//				+ "right\r\n"
//				+ "ring\r\n"
//				+ "rise\r\n"
//				+ "risk\r\n"
//				+ "river\r\n"
//				+ "road\r\n"
//				+ "rock\r\n"
//				+ "role\r\n"
//				+ "roll\r\n"
//				+ "romantic\r\n"
//				+ "roof\r\n"
//				+ "room\r\n"
//				+ "root\r\n"
//				+ "rope\r\n"
//				+ "rose\r\n"
//				+ "rough\r\n"
//				+ "roughly\r\n"
//				+ "round\r\n"
//				+ "route\r\n"
//				+ "routine\r\n"
//				+ "row\r\n"
//				+ "rub\r\n"
//				+ "rule\r\n"
//				+ "run\r\n"
//				+ "running\r\n"
//				+ "rural\r\n"
//				+ "rush\r\n"
//				+ "Russian\r\n"
//				+ "sacred\r\n"
//				+ "sad\r\n"
//				+ "safe\r\n"
//				+ "safety\r\n"
//				+ "sake\r\n"
//				+ "salad\r\n"
//				+ "salary\r\n"
//				+ "sale\r\n"
//				+ "sales\r\n"
//				+ "salt\r\n"
//				+ "same\r\n"
//				+ "sample\r\n"
//				+ "sanction\r\n"
//				+ "sand\r\n"
//				+ "satellite\r\n"
//				+ "satisfaction\r\n"
//				+ "satisfy\r\n"
//				+ "sauce\r\n"
//				+ "save\r\n"
//				+ "saving\r\n"
//				+ "say\r\n"
//				+ "scale\r\n"
//				+ "scandal\r\n"
//				+ "scared\r\n"
//				+ "scenario\r\n"
//				+ "scene\r\n"
//				+ "schedule\r\n"
//				+ "scheme\r\n"
//				+ "scholar\r\n"
//				+ "scholarship\r\n"
//				+ "school\r\n"
//				+ "science\r\n"
//				+ "scientific\r\n"
//				+ "scientist\r\n"
//				+ "scope\r\n"
//				+ "score\r\n"
//				+ "scream\r\n"
//				+ "screen\r\n"
//				+ "script\r\n"
//				+ "sea\r\n"
//				+ "search\r\n"
//				+ "season\r\n"
//				+ "seat\r\n"
//				+ "second\r\n"
//				+ "secret\r\n"
//				+ "secretary\r\n"
//				+ "section\r\n"
//				+ "sector\r\n"
//				+ "secure\r\n"
//				+ "security\r\n"
//				+ "see\r\n"
//				+ "seed\r\n"
//				+ "seek\r\n"
//				+ "seem\r\n"
//				+ "segment\r\n"
//				+ "seize\r\n"
//				+ "select\r\n"
//				+ "selection\r\n"
//				+ "self\r\n"
//				+ "sell\r\n"
//				+ "Senate\r\n"
//				+ "senator\r\n"
//				+ "send\r\n"
//				+ "senior\r\n"
//				+ "sense\r\n"
//				+ "sensitive\r\n"
//				+ "sentence\r\n"
//				+ "separate\r\n"
//				+ "sequence\r\n"
//				+ "series\r\n"
//				+ "serious\r\n"
//				+ "seriously\r\n"
//				+ "serve\r\n"
//				+ "service\r\n"
//				+ "session\r\n"
//				+ "set\r\n"
//				+ "setting\r\n"
//				+ "settle\r\n"
//				+ "settlement\r\n"
//				+ "seven\r\n"
//				+ "several\r\n"
//				+ "severe\r\n"
//				+ "sex\r\n"
//				+ "sexual\r\n"
//				+ "shade\r\n"
//				+ "shadow\r\n"
//				+ "shake\r\n"
//				+ "shall\r\n"
//				+ "shape\r\n"
//				+ "share\r\n"
//				+ "sharp\r\n"
//				+ "she\r\n"
//				+ "sheet\r\n"
//				+ "shelf\r\n"
//				+ "shell\r\n"
//				+ "shelter\r\n"
//				+ "shift\r\n"
//				+ "shine\r\n"
//				+ "ship\r\n"
//				+ "shirt\r\n"
//				+ "shit\r\n"
//				+ "shock\r\n"
//				+ "shoe\r\n"
//				+ "shoot\r\n"
//				+ "shooting\r\n"
//				+ "shop\r\n"
//				+ "shopping\r\n"
//				+ "shore\r\n"
//				+ "short\r\n"
//				+ "shortly\r\n"
//				+ "shot\r\n"
//				+ "should\r\n"
//				+ "shoulder\r\n"
//				+ "shout\r\n"
//				+ "show\r\n"
//				+ "shower\r\n"
//				+ "shrug\r\n"
//				+ "shut\r\n"
//				+ "sick\r\n"
//				+ "side\r\n"
//				+ "sigh\r\n"
//				+ "sight\r\n"
//				+ "sign\r\n"
//				+ "signal\r\n"
//				+ "significance\r\n"
//				+ "significant\r\n"
//				+ "significantly\r\n"
//				+ "silence\r\n"
//				+ "silent\r\n"
//				+ "silver\r\n"
//				+ "similar\r\n"
//				+ "similarly\r\n"
//				+ "simple\r\n"
//				+ "simply\r\n"
//				+ "sin\r\n"
//				+ "since\r\n"
//				+ "sing\r\n"
//				+ "singer\r\n"
//				+ "single\r\n"
//				+ "sink\r\n"
//				+ "sir\r\n"
//				+ "sister\r\n"
//				+ "sit\r\n"
//				+ "site\r\n"
//				+ "situation\r\n"
//				+ "six\r\n"
//				+ "size\r\n"
//				+ "ski\r\n"
//				+ "skill\r\n"
//				+ "skin\r\n"
//				+ "sky\r\n"
//				+ "slave\r\n"
//				+ "sleep\r\n"
//				+ "slice\r\n"
//				+ "slide\r\n"
//				+ "slight\r\n"
//				+ "slightly\r\n"
//				+ "slip\r\n"
//				+ "slow\r\n"
//				+ "slowly\r\n"
//				+ "small\r\n"
//				+ "smart\r\n"
//				+ "smell\r\n"
//				+ "smile\r\n"
//				+ "smoke\r\n"
//				+ "smooth\r\n"
//				+ "snap\r\n"
//				+ "snow\r\n"
//				+ "so\r\n"
//				+ "so-called\r\n"
//				+ "soccer\r\n"
//				+ "social\r\n"
//				+ "society\r\n"
//				+ "soft\r\n"
//				+ "software\r\n"
//				+ "soil\r\n"
//				+ "solar\r\n"
//				+ "soldier\r\n"
//				+ "solid\r\n"
//				+ "solution\r\n"
//				+ "solve\r\n"
//				+ "some\r\n"
//				+ "somebody\r\n"
//				+ "somehow\r\n"
//				+ "someone\r\n"
//				+ "something\r\n"
//				+ "sometimes\r\n"
//				+ "somewhat\r\n"
//				+ "somewhere\r\n"
//				+ "son\r\n"
//				+ "song\r\n"
//				+ "soon\r\n"
//				+ "sophisticated\r\n"
//				+ "sorry\r\n"
//				+ "sort\r\n"
//				+ "soul\r\n"
//				+ "sound\r\n"
//				+ "soup\r\n"
//				+ "source\r\n"
//				+ "south\r\n"
//				+ "southern\r\n"
//				+ "Soviet\r\n"
//				+ "space\r\n"
//				+ "Spanish\r\n"
//				+ "speak\r\n"
//				+ "speaker\r\n"
//				+ "special\r\n"
//				+ "specialist\r\n"
//				+ "species\r\n"
//				+ "specific\r\n"
//				+ "specifically\r\n"
//				+ "speech\r\n"
//				+ "speed\r\n"
//				+ "spend\r\n"
//				+ "spending\r\n"
//				+ "spin\r\n"
//				+ "spirit\r\n"
//				+ "spiritual\r\n"
//				+ "split\r\n"
//				+ "spokesman\r\n"
//				+ "sport\r\n"
//				+ "spot\r\n"
//				+ "spread\r\n"
//				+ "spring\r\n"
//				+ "square\r\n"
//				+ "squeeze\r\n"
//				+ "stability\r\n"
//				+ "stable\r\n"
//				+ "staff\r\n"
//				+ "stage\r\n"
//				+ "stair\r\n"
//				+ "stake\r\n"
//				+ "stand\r\n"
//				+ "standard\r\n"
//				+ "standing\r\n"
//				+ "star\r\n"
//				+ "stare\r\n"
//				+ "start\r\n"
//				+ "state\r\n"
//				+ "statement\r\n"
//				+ "station\r\n"
//				+ "statistics\r\n"
//				+ "status\r\n"
//				+ "stay\r\n"
//				+ "steady\r\n"
//				+ "steal\r\n"
//				+ "steel\r\n"
//				+ "step\r\n"
//				+ "stick\r\n"
//				+ "still\r\n"
//				+ "stir\r\n"
//				+ "stock\r\n"
//				+ "stomach\r\n"
//				+ "stone\r\n"
//				+ "stop\r\n"
//				+ "storage\r\n"
//				+ "store\r\n"
//				+ "storm\r\n"
//				+ "story\r\n"
//				+ "straight\r\n"
//				+ "strange\r\n"
//				+ "stranger\r\n"
//				+ "strategic\r\n"
//				+ "strategy\r\n"
//				+ "stream\r\n"
//				+ "street\r\n"
//				+ "strength\r\n"
//				+ "strengthen\r\n"
//				+ "stress\r\n"
//				+ "stretch\r\n"
//				+ "strike\r\n"
//				+ "string\r\n"
//				+ "strip\r\n"
//				+ "stroke\r\n"
//				+ "strong\r\n"
//				+ "strongly\r\n"
//				+ "structure\r\n"
//				+ "struggle\r\n"
//				+ "student\r\n"
//				+ "studio\r\n"
//				+ "study\r\n"
//				+ "stuff\r\n"
//				+ "stupid\r\n"
//				+ "style\r\n"
//				+ "subject\r\n"
//				+ "submit\r\n"
//				+ "subsequent\r\n"
//				+ "substance\r\n"
//				+ "substantial\r\n"
//				+ "succeed\r\n"
//				+ "success\r\n"
//				+ "successful\r\n"
//				+ "successfully\r\n"
//				+ "such\r\n"
//				+ "sudden\r\n"
//				+ "suddenly\r\n"
//				+ "sue\r\n"
//				+ "suffer\r\n"
//				+ "sufficient\r\n"
//				+ "sugar\r\n"
//				+ "suggest\r\n"
//				+ "suggestion\r\n"
//				+ "suicide\r\n"
//				+ "suit\r\n"
//				+ "summer\r\n"
//				+ "summit\r\n"
//				+ "sun\r\n"
//				+ "super\r\n"
//				+ "supply\r\n"
//				+ "support\r\n"
//				+ "supporter\r\n"
//				+ "suppose\r\n"
//				+ "supposed\r\n"
//				+ "Supreme\r\n"
//				+ "sure\r\n"
//				+ "surely\r\n"
//				+ "surface\r\n"
//				+ "surgery\r\n"
//				+ "surprise\r\n"
//				+ "surprised\r\n"
//				+ "surprising\r\n"
//				+ "surprisingly\r\n"
//				+ "surround\r\n"
//				+ "survey\r\n"
//				+ "survival\r\n"
//				+ "survive\r\n"
//				+ "survivor\r\n"
//				+ "suspect\r\n"
//				+ "sustain\r\n"
//				+ "swear\r\n"
//				+ "sweep\r\n"
//				+ "sweet\r\n"
//				+ "swim\r\n"
//				+ "swing\r\n"
//				+ "switch\r\n"
//				+ "symbol\r\n"
//				+ "symptom\r\n"
//				+ "system\r\n"
//				+ "table\r\n"
//				+ "tablespoon\r\n"
//				+ "tactic\r\n"
//				+ "tail\r\n"
//				+ "take\r\n"
//				+ "tale\r\n"
//				+ "talent\r\n"
//				+ "talk\r\n"
//				+ "tall\r\n"
//				+ "tank\r\n"
//				+ "tap\r\n"
//				+ "tape\r\n"
//				+ "target\r\n"
//				+ "task\r\n"
//				+ "taste\r\n"
//				+ "tax\r\n"
//				+ "taxpayer\r\n"
//				+ "tea\r\n"
//				+ "teach\r\n"
//				+ "teacher\r\n"
//				+ "teaching\r\n"
//				+ "team\r\n"
//				+ "tear\r\n"
//				+ "teaspoon\r\n"
//				+ "technical\r\n"
//				+ "technique\r\n"
//				+ "technology\r\n"
//				+ "teen\r\n"
//				+ "teenager\r\n"
//				+ "telephone\r\n"
//				+ "telescope\r\n"
//				+ "television\r\n"
//				+ "tell\r\n"
//				+ "temperature\r\n"
//				+ "temporary\r\n"
//				+ "ten\r\n"
//				+ "tend\r\n"
//				+ "tendency\r\n"
//				+ "tennis\r\n"
//				+ "tension\r\n"
//				+ "tent\r\n"
//				+ "term\r\n"
//				+ "terms\r\n"
//				+ "terrible\r\n"
//				+ "territory\r\n"
//				+ "terror\r\n"
//				+ "terrorism\r\n"
//				+ "terrorist\r\n"
//				+ "test\r\n"
//				+ "testify\r\n"
//				+ "testimony\r\n"
//				+ "testing\r\n"
//				+ "text\r\n"
//				+ "than\r\n"
//				+ "thank\r\n"
//				+ "thanks\r\n"
//				+ "that\r\n"
//				+ "the\r\n"
//				+ "theater\r\n"
//				+ "their\r\n"
//				+ "them\r\n"
//				+ "theme\r\n"
//				+ "themselves\r\n"
//				+ "then\r\n"
//				+ "theory\r\n"
//				+ "therapy\r\n"
//				+ "there\r\n"
//				+ "therefore\r\n"
//				+ "these\r\n"
//				+ "they\r\n"
//				+ "thick\r\n"
//				+ "thin\r\n"
//				+ "thing\r\n"
//				+ "think\r\n"
//				+ "thinking\r\n"
//				+ "third\r\n"
//				+ "thirty\r\n"
//				+ "this\r\n"
//				+ "those\r\n"
//				+ "though\r\n"
//				+ "thought\r\n"
//				+ "thousand\r\n"
//				+ "threat\r\n"
//				+ "threaten\r\n"
//				+ "three\r\n"
//				+ "throat\r\n"
//				+ "through\r\n"
//				+ "throughout\r\n"
//				+ "throw\r\n"
//				+ "thus\r\n"
//				+ "ticket\r\n"
//				+ "tie\r\n"
//				+ "tight\r\n"
//				+ "time\r\n"
//				+ "tiny\r\n"
//				+ "tip\r\n"
//				+ "tire\r\n"
//				+ "tired\r\n"
//				+ "tissue\r\n"
//				+ "title\r\n"
//				+ "to\r\n"
//				+ "tobacco\r\n"
//				+ "today\r\n"
//				+ "toe\r\n"
//				+ "together\r\n"
//				+ "tomato\r\n"
//				+ "tomorrow\r\n"
//				+ "tone\r\n"
//				+ "tongue\r\n"
//				+ "tonight\r\n"
//				+ "too\r\n"
//				+ "tool\r\n"
//				+ "tooth\r\n"
//				+ "top\r\n"
//				+ "topic\r\n"
//				+ "toss\r\n"
//				+ "total\r\n"
//				+ "totally\r\n"
//				+ "touch\r\n"
//				+ "tough\r\n"
//				+ "tour\r\n"
//				+ "tourist\r\n"
//				+ "tournament\r\n"
//				+ "toward\r\n"
//				+ "towards\r\n"
//				+ "tower\r\n"
//				+ "town\r\n"
//				+ "toy\r\n"
//				+ "trace\r\n"
//				+ "track\r\n"
//				+ "trade\r\n"
//				+ "tradition\r\n"
//				+ "traditional\r\n"
//				+ "traffic\r\n"
//				+ "tragedy\r\n"
//				+ "trail\r\n"
//				+ "train\r\n"
//				+ "training\r\n"
//				+ "transfer\r\n"
//				+ "transform\r\n"
//				+ "transformation\r\n"
//				+ "transition\r\n"
//				+ "translate\r\n"
//				+ "transportation\r\n"
//				+ "travel\r\n"
//				+ "treat\r\n"
//				+ "treatment\r\n"
//				+ "treaty\r\n"
//				+ "tree\r\n"
//				+ "tremendous\r\n"
//				+ "trend\r\n"
//				+ "trial\r\n"
//				+ "tribe\r\n"
//				+ "trick\r\n"
//				+ "trip\r\n"
//				+ "troop\r\n"
//				+ "trouble\r\n"
//				+ "truck\r\n"
//				+ "true\r\n"
//				+ "truly\r\n"
//				+ "trust\r\n"
//				+ "truth\r\n"
//				+ "try\r\n"
//				+ "tube\r\n"
//				+ "tunnel\r\n"
//				+ "turn\r\n"
//				+ "TV\r\n"
//				+ "twelve\r\n"
//				+ "twenty\r\n"
//				+ "twice\r\n"
//				+ "twin\r\n"
//				+ "two\r\n"
//				+ "type\r\n"
//				+ "typical\r\n"
//				+ "typically\r\n"
//				+ "ugly\r\n"
//				+ "ultimate\r\n"
//				+ "ultimately\r\n"
//				+ "unable\r\n"
//				+ "uncle\r\n"
//				+ "under\r\n"
//				+ "undergo\r\n"
//				+ "understand\r\n"
//				+ "understanding\r\n"
//				+ "unfortunately\r\n"
//				+ "uniform\r\n"
//				+ "union\r\n"
//				+ "unique\r\n"
//				+ "unit\r\n"
//				+ "United\r\n"
//				+ "universal\r\n"
//				+ "universe\r\n"
//				+ "university\r\n"
//				+ "unknown\r\n"
//				+ "unless\r\n"
//				+ "unlike\r\n"
//				+ "unlikely\r\n"
//				+ "until\r\n"
//				+ "unusual\r\n"
//				+ "up\r\n"
//				+ "upon\r\n"
//				+ "upper\r\n"
//				+ "urban\r\n"
//				+ "urge\r\n"
//				+ "us\r\n"
//				+ "use\r\n"
//				+ "used\r\n"
//				+ "useful\r\n"
//				+ "user\r\n"
//				+ "usual\r\n"
//				+ "usually\r\n"
//				+ "utility\r\n"
//				+ "vacation\r\n"
//				+ "valley\r\n"
//				+ "valuable\r\n"
//				+ "value\r\n"
//				+ "variable\r\n"
//				+ "variation\r\n"
//				+ "variety\r\n"
//				+ "various\r\n"
//				+ "vary\r\n"
//				+ "vast\r\n"
//				+ "vegetable\r\n"
//				+ "vehicle\r\n"
//				+ "venture\r\n"
//				+ "version\r\n"
//				+ "versus\r\n"
//				+ "very\r\n"
//				+ "vessel\r\n"
//				+ "veteran\r\n"
//				+ "via\r\n"
//				+ "victim\r\n"
//				+ "victory\r\n"
//				+ "video\r\n"
//				+ "view\r\n"
//				+ "viewer\r\n"
//				+ "village\r\n"
//				+ "violate\r\n"
//				+ "violation\r\n"
//				+ "violence\r\n"
//				+ "violent\r\n"
//				+ "virtually\r\n"
//				+ "virtue\r\n"
//				+ "virus\r\n"
//				+ "visible\r\n"
//				+ "vision\r\n"
//				+ "visit\r\n"
//				+ "visitor\r\n"
//				+ "visual\r\n"
//				+ "vital\r\n"
//				+ "voice\r\n"
//				+ "volume\r\n"
//				+ "volunteer\r\n"
//				+ "vote\r\n"
//				+ "voter\r\n"
//				+ "vs\r\n"
//				+ "vulnerable\r\n"
//				+ "wage\r\n"
//				+ "wait\r\n"
//				+ "wake\r\n"
//				+ "walk\r\n"
//				+ "wall\r\n"
//				+ "wander\r\n"
//				+ "want\r\n"
//				+ "war\r\n"
//				+ "warm\r\n"
//				+ "warn\r\n"
//				+ "warning\r\n"
//				+ "wash\r\n"
//				+ "waste\r\n"
//				+ "watch\r\n"
//				+ "water\r\n"
//				+ "wave\r\n"
//				+ "way\r\n"
//				+ "we\r\n"
//				+ "weak\r\n"
//				+ "wealth\r\n"
//				+ "wealthy\r\n"
//				+ "weapon\r\n"
//				+ "wear\r\n"
//				+ "weather\r\n"
//				+ "wedding\r\n"
//				+ "week\r\n"
//				+ "weekend\r\n"
//				+ "weekly\r\n"
//				+ "weigh\r\n"
//				+ "weight\r\n"
//				+ "welcome\r\n"
//				+ "welfare\r\n"
//				+ "well\r\n"
//				+ "west\r\n"
//				+ "western\r\n"
//				+ "wet\r\n"
//				+ "what\r\n"
//				+ "whatever\r\n"
//				+ "wheel\r\n"
//				+ "when\r\n"
//				+ "whenever\r\n"
//				+ "where\r\n"
//				+ "whereas\r\n"
//				+ "whether\r\n"
//				+ "which\r\n"
//				+ "while\r\n"
//				+ "whisper\r\n"
//				+ "white\r\n"
//				+ "who\r\n"
//				+ "whole\r\n"
//				+ "whom\r\n"
//				+ "whose\r\n"
//				+ "why\r\n"
//				+ "wide\r\n"
//				+ "widely\r\n"
//				+ "widespread\r\n"
//				+ "wife\r\n"
//				+ "wild\r\n"
//				+ "will\r\n"
//				+ "willing\r\n"
//				+ "win\r\n"
//				+ "wind\r\n"
//				+ "window\r\n"
//				+ "wine\r\n"
//				+ "wing\r\n"
//				+ "winner\r\n"
//				+ "winter\r\n"
//				+ "wipe\r\n"
//				+ "wire\r\n"
//				+ "wisdom\r\n"
//				+ "wise\r\n"
//				+ "wish\r\n"
//				+ "with\r\n"
//				+ "withdraw\r\n"
//				+ "within\r\n"
//				+ "without\r\n"
//				+ "witness\r\n"
//				+ "woman\r\n"
//				+ "wonder\r\n"
//				+ "wonderful\r\n"
//				+ "wood\r\n"
//				+ "wooden\r\n"
//				+ "word\r\n"
//				+ "work\r\n"
//				+ "worker\r\n"
//				+ "working\r\n"
//				+ "works\r\n"
//				+ "workshop\r\n"
//				+ "world\r\n"
//				+ "worried\r\n"
//				+ "worry\r\n"
//				+ "worth\r\n"
//				+ "would\r\n"
//				+ "wound\r\n"
//				+ "wrap\r\n"
//				+ "write\r\n"
//				+ "writer\r\n"
//				+ "writing\r\n"
//				+ "wrong\r\n"
//				+ "yard\r\n"
//				+ "yeah\r\n"
//				+ "year\r\n"
//				+ "yell\r\n"
//				+ "yellow\r\n"
//				+ "yes\r\n"
//				+ "yesterday\r\n"
//				+ "yet\r\n"
//				+ "yield\r\n"
//				+ "you\r\n"
//				+ "young\r\n"
//				+ "your\r\n"
//				+ "yours\r\n"
//				+ "yourself\r\n"
//				+ "youth\r\n"
//				+ "zone");
//		
//		bw.close();
		
		
		//LEITURA E CONFIGURAÇÃO DAS PALAVRAS DO ARQUIVO "3 MIL PALAVRAS EM INGLES[MAIS USADAS]";
		
		
		FileInputStream fis = new FileInputStream("3mpei.txt");
		InputStreamReader isr = new InputStreamReader(fis);
		BufferedReader br = new BufferedReader(isr);
		
		
		
		
		
		
		Palavra palavras = new Palavra();
		LinkedList<String> palavraConjunto = new LinkedList<String>();
		palavras.setPalavra(palavraConjunto);
		
		
		
		
		
		
		for(int i = 0; i < 3000; i++) {
			String lerLinha = br.readLine();
			palavraConjunto.add(i, lerLinha);
			
		};
		
		
		br.close();
		
		System.out.println("Seja bem-vindo Marujo! Vamos aprender mais palavras em Inglês?"
		+ "É fácil digite uma palavra da lista das três mil mais faladas,\r\n"
		+ " e eu te mostro se ela está contida na lista!\r\n"
		+ "Sugiro iniciar pelas oito primeiras e depois você vai avançando.\r\n"
		+ "Este programa trabalha com palavras de 8 em 8.\r\n"
		+ "Mas você pode modificá-lo para o que for melhor pra você.\r\n"
		+ "De acordo com sua evolução você que é DEV deve \r\n"
		+ "ir alterando as configurações do loop de respostas\r\n"
		+ "Escolha uma frequência na semana para aprendê-las. E vamos nessa!\r\n"
		+ "Nosso programa trabalha com a ordenação das palavras da lista em ordem alfabética.\r\n"
		+ "Então, digite a primeira e veja se ela está contida na lista, se sim\r\n"
		+ ", você ganhará um grande Parabéns e o direito a conferir com exatidão que ela está\r\n"
		+ "na lista. E faça assim também com as outras palavras.\r\n"
		+ "Após verificação da palavra escrita em inglês, verifica-se a tradução da \r\n"
		+ "mesma. Se houver mais de 1 significado, digita-se com apenas 1 traço entre eles.\r\n"
		+ "É importante você memorizar a ordem das 8 palavras que você escolher\r\n"
		+ ", pois além de exercitar sua memória, o programa irá funcionar corretamente.\r\n"
		+ "Para parar o programa existem quatro jeitos mais comuns: \r\n"
		+ "1º fechando o eclipse.\\r\\n"
		+ "2º Recarregando o programa.\r\n"
		+ "3º Digitando as 8 palavras corretamente e depois digite uma frase bonita como "
		+ "agradecimento por este bom exercício que você fez e aperte enter.\r\n"
		+ "Observação: se você digitar uma palavra errada, apenas vai perder uma chance"
		+ "de oito que você tem para as palavras em inglês e 1 em 8 para as traduções.");
		
		
		
		//PARA INTRODUZIR MAIS TRADUÇÕES, É RECOMENDADO DAR UM CTRL+7 NAS PARTES DO CÓDIGO QUE NÃO DIZ
		//RESPEITO A ISSO. O CÓDIGO FOI FEITO DESSA MANEIRA SEM SEPARAR ESSAS FUNÇÕES EM OUTRA PÁGINA DE
		//CÓDIGO PORQUE O DESENVOLVEDOR CRIADOR DO PROGRAMA TEVE PROBLEMAS QUANDO TENTOU ISTO.
		
		
		
		//INSTRUÇÕES PARA ORGANIZAR AS TRADUÇÕES:
		
		
				//ESCRITA DAS TRADUÇÕES:
				
//				FileOutputStream fos = new FileOutputStream("significados.txt");
//				OutputStreamWriter osw = new OutputStreamWriter(fos);
//				BufferedWriter bw = new BufferedWriter(osw);
//				
//				bw.write("um-uma\r\n"
//						+ "abandonar\r\n"
//						+ "habilidade\r\n"
//						+ "capaz-apto\r\n"
//						+ "aborto\r\n"
//						+ "sobre\r\n"
//						+ "acima\r\n"
//						+ "no-estrangeiro-no-exterior");
//				
//				bw.close();
				
				
				//LEITURA DAS TRADUÇÕES:
				
				FileInputStream fist = new FileInputStream("significados.txt");
				InputStreamReader isrt = new InputStreamReader(fist);
				BufferedReader brt = new BufferedReader(isrt);
				
				
				
				
				Traducao traducoes = new Traducao();
				LinkedList<String> traducaoConjunto = new LinkedList<String>();
				traducoes.setTraducao(traducaoConjunto);
				
				
				for(int o = 0; o < 8; o++) {
					String lerLinhaT = brt.readLine();
					traducaoConjunto.add(o, lerLinhaT);
				}
				
				brt.close();

				
		
		
		
		
		
		Scanner sc = new Scanner(System.in);
		
		
		for(int f = 0; f < 8; f++) {
			
			String variavel = sc.next();
			
			
			while(palavras.getPalavra().get(0).equalsIgnoreCase(variavel)) {
				if(palavras.getPalavra().get(0).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a palavra! Sua palavra é: " + palavras.getPalavra().get(0));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando "
							+ "para obter êxito com as palavras em inglês." );
				};
				
				variavel = sc.next();
				
				if(traducoes.getTraducoes().get(0).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você já acertou a(s) tradução(ões)! " + " Traduzindo fica: "+ traducoes.getTraducoes().get(0));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando"
							+ " para obter êxito com as traduções." );
				};
				
				
				break;
				
			};
			
			
			while(palavras.getPalavra().get(1).equalsIgnoreCase(variavel)) {
				if(palavras.getPalavra().get(1).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a palavra! Sua palavra é: " + palavras.getPalavra().get(1));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando "
							+ "para obter êxito com as palavras em inglês." );
				};
				
				variavel = sc.next();
				
				if(traducoes.getTraducoes().get(1).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a(s) tradução(ões)! " + " Traduzindo fica: "+ traducoes.getTraducoes().get(1));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando"
							+ " para obter êxito com as traduções." );
				};
				break;
				
			};
			
			
			while(palavras.getPalavra().get(2).equalsIgnoreCase(variavel)) {
				if(palavras.getPalavra().get(2).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a palavra! Sua palavra é: " + palavras.getPalavra().get(2));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando "
							+ "para obter êxito com as palavras em inglês." );
				};
				
				variavel = sc.next();
				
				if(traducoes.getTraducoes().get(2).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a(s) tradução(ões)! " + " Traduzindo fica: "+ traducoes.getTraducoes().get(2));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando"
							+ " para obter êxito com as traduções." );
				};
				break;
				
			};
			
			
			while(palavras.getPalavra().get(3).equalsIgnoreCase(variavel)) {
				if(palavras.getPalavra().get(3).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a palavra! Sua palavra é: " + palavras.getPalavra().get(3));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando "
							+ "para obter êxito com as palavras em inglês." );
				};
				
				variavel = sc.next();
				
				if(traducoes.getTraducoes().get(3).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a(s) tradução(ões)! Traduzindo fica: "+ traducoes.getTraducoes().get(3));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando"
							+ " para obter êxito com as traduções." );
				};
				
				break;
				
			};
			
			
			while(palavras.getPalavra().get(4).equalsIgnoreCase(variavel)) {
				if(palavras.getPalavra().get(4).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a palavra! Sua palavra é: " + palavras.getPalavra().get(4));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando "
							+ "para obter êxito com as palavras em inglês." );
				};
				
				variavel = sc.next();
				
				if(traducoes.getTraducoes().get(4).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a(s) tradução(ões)! " + " Traduzindo fica: "+ traducoes.getTraducoes().get(4));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando"
							+ " para obter êxito com as traduções." );
				};
				
				break;
				
			};
			
			
			while(palavras.getPalavra().get(5).equalsIgnoreCase(variavel)) {
				if(palavras.getPalavra().get(5).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a palavra! Sua palavra é: " + palavras.getPalavra().get(5));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando "
							+ "para obter êxito com as palavras em inglês." );
				};
				
				variavel = sc.next();
				
				if(traducoes.getTraducoes().get(5).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou  a(s) tradução(ões)! " + " Traduzindo fica: "+ traducoes.getTraducoes().get(5));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando"
							+ " para obter êxito com as traduções." );
				};
				
				break;
				
			};
			
			
			while(palavras.getPalavra().get(6).equalsIgnoreCase(variavel)) {
				if(palavras.getPalavra().get(6).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a palavra! Sua palavra é: " + palavras.getPalavra().get(6));
					
//				} else {
//					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
//							+ " você tem " + (8 - f) + " chances faltando "
//							+ "para obter êxito com as palavras em inglês." );
				};
				
				variavel = sc.next();
				
				if(traducoes.getTraducoes().get(6).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a(s) tradução(ões)! " + " Traduzindo fica: "+ traducoes.getTraducoes().get(6));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando"
							+ " para obter êxito com as traduções." );
				};
				
				break;
				
			};
			
			
			while(palavras.getPalavra().get(7).equalsIgnoreCase(variavel)) {
				if(palavras.getPalavra().get(7).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a palavra! Sua palavra é: " + palavras.getPalavra().get(7));
					
//				} else {
//					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
//							+ " você tem " + (8 - f) + " chances faltando "
//							+ "para obter êxito com as palavras em inglês." );
				};
				
				variavel = sc.next();
				
				if(traducoes.getTraducoes().get(7).equalsIgnoreCase(variavel)) {
					System.out.println("Parabéns você acertou a(s) tradução(ões)! " + " Traduzindo fica: "+ traducoes.getTraducoes().get(7));
					
				} else {
					System.out.println("Sinto muito você não acertou ainda. Tente novamente! "
							+ " você tem " + (8 - f) + " chances faltando"
							+ " para obter êxito com as traduções." );
				};	
				
				break;
				
			};
			
			
			
		};
		
		sc.close();
		
		
		
			
		
	}
}
